"use client";
import Link from"next/link";import{ArrowLeft,ArrowRight,CheckCircle2,Clock3,Flag,Headphones,Trophy}from"lucide-react";import{useEffect,useMemo,useState}from"react";import{AppHeader}from"@/components/Brand";import Sidebar from"@/components/Sidebar";import{useProfile}from"@/components/ProfileBadge";import AudioPlayer from"./AudioPlayer";import{checkAnswer}from"@/lib/answer-checker";import{createClient}from"@/lib/supabase/client";import{saveWritingSubmission}from"@/lib/supabase/writing-sync";import{createFullSession,FULL_ACTIVE_KEY,FULL_HISTORY_KEY,FULL_LAST_IDS_KEY,FULL_SECTION_ORDER,isResumableFullSession,isSupportedFullGrade,nextFullSectionIndex,resolveSessionQuestions,resolveSessionWriting,updateFullHistory,scoreFullObjectiveSections,type FullHistory,type FullQuestion,type FullSession}from"@/lib/full-olympiad";
import{resolveFullListeningGroup}from"@/lib/full-olympiad";import type{ListeningGroup}from"@/lib/standalone-training";
import{validatedListeningGroupsForGrade}from"@/lib/listening-registry";
const labels={listening:"Listening",reading:"Reading","use-of-english":"Use of English",writing:"Writing"}as const;
const read=<T,>(key:string,fallback:T):T=>{try{return JSON.parse(localStorage.getItem(key)||"")as T}catch{return fallback}};
type StudentClassMarker={class_id?:string|null};
const hasTeacherClass=()=>!!read<StudentClassMarker|null>("studentClass",null)?.class_id;
const words=(text:string)=>text.trim()?text.trim().split(/\s+/).length:0;
function optionValue(option:string){return option.match(/^[A-F](?=\s|$)/i)?.[0].toLowerCase()||option}
function friendlyWritingError(message?:string){const text=(message||"").toLowerCase();if(text.includes("failed to fetch")||text.includes("network")||text.includes("fetcherror"))return"Не удалось связаться с сервером. Проверьте интернет и попробуйте отправить Writing ещё раз.";if(text.includes("no active supabase session"))return"Профиль сохранён локально, поэтому отправка учителю сейчас недоступна.";return message||"Не удалось отправить Writing. Попробуйте ещё раз."}
// The post-mount storage read intentionally keeps the server render deterministic.
// eslint-disable-next-line react-hooks/set-state-in-effect
export default function FullOlympiadTraining(){const profile=useProfile(),grade=Number(profile.grade),listeningAvailable=grade<9||validatedListeningGroupsForGrade(grade).length>0,[session,setSession]=useState<FullSession|null>(null),[ready,setReady]=useState(false),[error,setError]=useState(""),[submitting,setSubmitting]=useState(false),[teacherLinked,setTeacherLinked]=useState(false);useEffect(()=>{const stored=read<FullSession|null>(FULL_ACTIVE_KEY,null);setSession(isResumableFullSession(stored,grade)?stored:null);setTeacherLinked(hasTeacherClass());setReady(true)},[grade]);useEffect(()=>{if(session&&!session.completedAt)localStorage.setItem(FULL_ACTIVE_KEY,JSON.stringify(session));else localStorage.removeItem(FULL_ACTIVE_KEY)},[session]);
 useEffect(()=>{if(!session?.completedAt||session.writingStatus!=="pending"||!teacherLinked)return;let active=true;(async()=>{try{const{data}=await createClient().from("writing_reviews").select("score,max_score,teacher_comment,status").eq("attempt_id",session.id).maybeSingle();if(active&&data?.status==="reviewed")setSession(value=>value?{...value,writingStatus:"reviewed",writingReview:{score:data.score,maxScore:data.max_score,comment:data.teacher_comment}}:value)}catch{}})();return()=>{active=false}},[session?.completedAt,session?.id,session?.writingStatus,teacherLinked]);
 const all=useMemo(()=>session?resolveSessionQuestions(session):[],[session]),section=FULL_SECTION_ORDER[session?.sectionIndex||0],questions=all.filter(q=>q.section===section),answered=questions.filter(q=>session?.answers[q.id]?.trim()).length;
 function begin(){localStorage.removeItem(FULL_ACTIVE_KEY);setSession(createFullSession(grade,read<FullHistory>(FULL_HISTORY_KEY,{}),read<string[]>(FULL_LAST_IDS_KEY,[])));setError("");window.scrollTo({top:0})}
 function answer(id:string,response:string){setSession(current=>current?{...current,answers:{...current.answers,[id]:response}}:current)}
 function next(){if(!session)return;const nextIndex=nextFullSectionIndex(session);if(nextIndex!==session.sectionIndex){setSession({...session,sectionIndex:nextIndex});window.scrollTo({top:0,behavior:"smooth"})}}
 function finishFullSession(completedAt:string,writingStatus:NonNullable<FullSession["writingStatus"]>){if(!session)return;const task=resolveSessionWriting(session),objective=all,history=updateFullHistory(read(FULL_HISTORY_KEY,{}),objective,session.answers,(q,a)=>checkAnswer(q,a)===true),oldWriting=history[task.id]||{seen:0,incorrect:0};history[task.id]={seen:oldWriting.seen+1,incorrect:oldWriting.incorrect};localStorage.setItem(FULL_HISTORY_KEY,JSON.stringify(history));const lastIds=[session.listeningGroupId,...objective.filter(q=>q.section!=="listening").map(q=>q.id),task.id].filter((value):value is string=>!!value);localStorage.setItem(FULL_LAST_IDS_KEY,JSON.stringify(lastIds));localStorage.removeItem(FULL_ACTIVE_KEY);setSession({...session,completedAt,writingStatus});window.dispatchEvent(new Event("training-progress"));window.scrollTo({top:0})}
 async function submitWriting(){if(!session)return;const task=resolveSessionWriting(session),text=session.writingText.trim();if(!text){setError("Напиши работу перед завершением тренировки.");return}setSubmitting(true);setError("");const completedAt=new Date().toISOString();if(!teacherLinked){setSubmitting(false);finishFullSession(completedAt,"local");return}const result=await saveWritingSubmission({attemptId:session.id,startedAt:session.startedAt,completedAt,task,text,wordCount:words(text),headlinePresent:text.split("\n")[0]?.trim().length>0});setSubmitting(false);if(result.status==="error"){setError(friendlyWritingError(result.error));return}finishFullSession(completedAt,"pending")}
 if(!ready)return null;if(!isSupportedFullGrade(grade))return <main className="portal training adaptive-page"><AppHeader blue/><div className="adaptive-shell"><Link href="/dashboard"><ArrowLeft/> Главная</Link><section className="adaptive-empty"><Flag/><h1>Полная тренировка доступна для 7–11 классов.</h1></section></div></main>;
 if(!session)return <main className="portal training adaptive-page"><AppHeader blue/><div className="full-start"><Link href="/dashboard"><ArrowLeft/> На главную</Link><section><Trophy/><span>ОЛИМПИАДНЫЙ ФОРМАТ</span><h1>Полная олимпиадная тренировка</h1><p>Пройди письменную часть олимпиады целиком</p><div className="full-sequence">{FULL_SECTION_ORDER.map((s,i)=><span key={s}><b>{i+1}</b>{labels[s]}</span>)}</div>{!listeningAvailable&&<p className="writing-warning">Аудирование для этого класса временно недоступно. Тренировка начнётся с Reading.</p>}{error&&<p className="writing-warning">{error}</p>}<button className="primary blue" onClick={begin}>Начать полную тренировку <ArrowRight/></button><small>Speaking проходит отдельно и не входит в этот раунд.</small></section></div></main>;
 if(session.completedAt){const{rows:sectionRows,correct,total,percentage}=scoreFullObjectiveSections(all,session.answers,(q,a)=>checkAnswer(q,a)===true),review=session.writingReview,waitingForTeacher=session.writingStatus==="pending";return <main className="portal training adaptive-page"><AppHeader blue/><div className="full-result"><section><Trophy/><span>ПОЛНАЯ ТРЕНИРОВКА</span><h1>Письменная часть завершена</h1><strong>{correct} / {total} · {percentage}%</strong><p>Результат по объективным разделам с автоматической проверкой</p><div className="full-breakdown">{sectionRows.map(row=><div key={row.section}><b>{labels[row.section]}</b><span>{row.correct}/{row.total}</span></div>)}<div><b>Writing</b><span>{review?review.score+"/"+review.maxScore:waitingForTeacher?"На проверке":"Сохранено без оценки"}</span></div></div>{review?<><h2>Работа проверена</h2>{review.comment&&<p>Комментарий учителя: {review.comment}</p>}<strong className="full-final">Итого: {correct+review.score} / {total+review.maxScore}</strong></>:waitingForTeacher?<p className="full-pending"><Clock3/> Итоговый результат появится после проверки Writing учителем.</p>:<p className="full-pending"><Clock3/> Writing сохранён локально. Автопроверка сейчас недоступна, поэтому общий процент рассчитан по Listening, Reading и Use of English.</p>}<div className="full-result-actions"><button onClick={begin}>Новый полный раунд</button><Link href="/dashboard">На главную</Link></div></section></div></main>}
 const progress=Math.round((session.sectionIndex+answered/Math.max(questions.length,1))/4*100),listeningGroup=resolveFullListeningGroup(session);return <main className="portal training adaptive-page"><AppHeader blue/><div className="adaptive-layout"><Sidebar active={labels[section]}/><section className="adaptive-main"><header className="full-run-top"><Link href="/dashboard"><ArrowLeft/> Сохранить и выйти</Link><div><b>Полная тренировка</b><span>Раздел {session.sectionIndex+1} из 4 · {labels[section]}</span></div><strong>{progress}%</strong></header><div className="full-progress"><i style={{width:`${progress}%`}}/></div>{section==="writing"?<Writing session={session} setSession={setSession} onSubmit={submitWriting} submitting={submitting} error={error} teacherLinked={teacherLinked}/>:<Objective section={section} questions={questions} answers={session.answers} onAnswer={answer} listeningGroup={listeningGroup}/>}<button className="primary blue adaptive-finish" disabled={section!=="writing"&&answered<questions.length} onClick={section==="writing"?submitWriting:next}>{section==="writing"?(submitting?(teacherLinked?"Отправляем…":"Завершаем…"):teacherLinked?"Завершить и отправить Writing":"Завершить тренировку"):"Перейти к следующему разделу"} <ArrowRight/></button>{section!=="writing"&&answered<questions.length&&<p className="full-answer-note">Ответь на все задания, чтобы продолжить.</p>}</section></div></main>}
function Objective({section,questions,answers,onAnswer,listeningGroup}:{section:string;questions:FullQuestion[];answers:Record<string,string>;onAnswer:(id:string,value:string)=>void;listeningGroup:ListeningGroup|null}){const groups=[...new Set(questions.map(q=>q.groupId||q.id))];return <><section className="full-section-title"><span>{section==="listening"?<Headphones/>:<CheckCircle2/>}</span><div><small>ТЕКУЩИЙ РАЗДЕЛ</small><h1>{labels[section as keyof typeof labels]}</h1><p>Выполни задания по порядку. Ответы сохраняются автоматически.</p></div></section>{section==="listening"&&!listeningGroup&&<p className="writing-warning">Аудирование для этого класса временно недоступно</p>}{section==="listening"&&listeningGroup&&(listeningGroup.audioMode==="file"&&listeningGroup.audioSrc?<audio className="full-audio" controls preload="metadata" src={listeningGroup.audioSrc}/>:<AudioPlayer text={listeningGroup.script||""} maxPlays={2} lang="en-GB" rate={.9}/>)}{groups.map(group=>{const items=questions.filter(q=>(q.groupId||q.id)===group),first=items[0];return <section className="adaptive-question-group" key={group}><h2>{first.instruction}</h2>{first.passage&&<div className="adaptive-passage">{first.passage}</div>}{items.map((q,index)=><article key={q.id}><div className="question-label"><span>{questions.indexOf(q)+1}</span><small>{q.skill} · {q.subskill}</small></div><h3>{q.text}</h3>{q.options.length?<div className="adaptive-options">{q.options.map(option=>{const value=optionValue(option);return <label key={option}><input type="radio" name={q.id} checked={answers[q.id]===value} onChange={()=>onAnswer(q.id,value)}/><span>{option}</span></label>})}</div>:<input className="adaptive-input" value={answers[q.id]||""} onChange={event=>onAnswer(q.id,event.target.value)} aria-label={`Ответ на задание ${index+1}`}/>}</article>)}</section>})}</>}
function Writing({session,setSession,onSubmit,submitting,error,teacherLinked}:{session:FullSession;setSession:React.Dispatch<React.SetStateAction<FullSession|null>>;onSubmit:()=>void;submitting:boolean;error:string;teacherLinked:boolean}){const task=resolveSessionWriting(session),count=words(session.writingText);return <section className="full-writing"><small>РАЗДЕЛ 4 ИЗ 4</small><h1>Writing</h1><p className="full-writing-prompt">{task.text}</p>{task.requirements&&<ul>{task.requirements.map(item=><li key={item}>{item}</li>)}</ul>}<div className="full-writing-meta"><span>Рекомендуемый объём: {task.wordLimit?.min}–{task.wordLimit?.max} слов</span><b>{count} слов</b></div><textarea value={session.writingText} onChange={event=>setSession(value=>value?{...value,writingText:event.target.value}:value)} placeholder="Напиши ответ здесь…"/><p>{teacherLinked?"Writing проверит учитель. До проверки будет показан только предварительный результат объективных разделов.":"Writing будет сохранён локально. Автопроверка сейчас недоступна, поэтому итоговый процент будет рассчитан по объективным разделам."}</p>{error&&<p className="writing-warning">{error}</p>}<button type="button" hidden onClick={onSubmit} disabled={submitting}>Отправить</button></section>}
