"use client";
/* eslint-disable react-hooks/preserve-manual-memoization, react-hooks/set-state-in-effect */
import Link from"next/link";
import{ArrowLeft,BookOpen,Headphones,Play,Puzzle}from"lucide-react";
import{useCallback,useEffect,useMemo,useState}from"react";
import{AppHeader}from"@/components/Brand";
import{useProfile}from"@/components/ProfileBadge";
import{grade9OriginalQuestionBank}from"@/data/questions/grade-9/original";
import{grade9Reading2023Verified,grade9UseOfEnglish2023Verified}from"@/data/questions/grade-9/official/2023/verified";
import{official2024ForGrade}from"@/data/questions/grade-9-10/official-2024";
import{official2025ForGrade}from"@/data/questions/grade-9-10/official-2025";
import{grade11Registry,seniorOriginalSet}from"@/data/questions/grade-10-11";
import{grade10UseOfEnglish2022Verified,grade11UseOfEnglish2022Verified}from"@/data/questions/grade-10-11/official-2022";
import{grade10Reading2022Verified,grade11Reading2022Verified}from"@/data/questions/grade-10-11/official-2022-reading";
import{grade10Reading2023Verified,grade10UseOfEnglish2023Verified}from"@/data/questions/grade-10-11/official-2023-grade10";
import type{QuestionBankItem,QuestionSet,Section}from"@/data/questions/types";
import{createClient}from"@/lib/supabase/client";
import{validatedListeningGroupsForGrade}from"@/lib/listening-registry";
import{completeStandaloneHistory,createStandaloneListeningSession,createStandaloneSession,isResumableStandaloneSession,listeningGroupsFromSets,resolveStandaloneListeningGroup,resolveStandaloneQuestions,selectableQuestions,standaloneActiveKey,standaloneHistoryKey,standaloneLastKey,type ListeningGroup,type StandaloneHistory,type StandaloneSession}from"@/lib/standalone-training";
import OfficialSection from"./OfficialSection";

type VariantKind="original"|"dataset";export const defaultTrainingVariantOrder:VariantKind[]=["original","dataset"];
const sectionName:Record<Section,string>={listening:"Listening",reading:"Reading","use-of-english":"Use of English",writing:"Writing"};
const sectionIcon=(section:Section)=>section==="listening"?<Headphones/>:section==="use-of-english"?<Puzzle/>:<BookOpen/>;
const read=<T,>(key:string,fallback:T):T=>{try{return JSON.parse(localStorage.getItem(key)||"")as T}catch{return fallback}};
function originalSet(section:Section):QuestionSet|null{const items=grade9OriginalQuestionBank.filter(q=>q.section===section&&q.acceptedAnswers.length&&!q.needsReview).map(q=>({...q,grade:9,options:q.options.map(o=>`${o.id.toUpperCase()} ${o.label}`)})as unknown as QuestionBankItem);return items.length?{id:`olab-original-${section}`,title:sectionName[section],section,instruction:`Выполни задания раздела ${sectionName[section]}.`,items}:null}
const canAutoScore=(set:QuestionSet)=>set.items.length>0&&set.items.every(item=>item.acceptedAnswers.length>0&&!item.needsReview);
const grade10Official2024=official2024ForGrade(10);
const grade10Official2025=official2025ForGrade(10);

export default function GradeOfficialSection({junior,grade9}:{junior:QuestionSet|QuestionSet[];grade9:QuestionSet[];order?:VariantKind[]}){
 const profile=useProfile(),grade=Number(profile.grade),juniorSets=useMemo(()=>Array.isArray(junior)?junior:[junior],[junior]),section=grade9[0]?.section||juniorSets[0]?.section||"reading",[active,setActive]=useState<{session:StandaloneSession;set:QuestionSet}|null>(null),[ready,setReady]=useState(false);
 const sets=useMemo(()=>{if(grade===7||grade===8)return juniorSets.filter(canAutoScore);if(grade===9){const original=originalSet(section),set2023=section==="reading"?grade9Reading2023Verified:section==="use-of-english"?grade9UseOfEnglish2023Verified:null;return[...(original?[original]:[]),...grade9.filter(canAutoScore),...(set2023&&canAutoScore(set2023)?[set2023]:[])]}if(grade===10){const original=seniorOriginalSet(10,section),set2022=section==="reading"?grade10Reading2022Verified:section==="use-of-english"?grade10UseOfEnglish2022Verified:null,set2023=section==="reading"?grade10Reading2023Verified:section==="use-of-english"?grade10UseOfEnglish2023Verified:null,set2024=grade10Official2024[section as keyof typeof grade10Official2024],set2025=grade10Official2025[section as keyof typeof grade10Official2025];return[...(original?[original]:[]),...(set2022&&canAutoScore(set2022)?[set2022]:[]),...(set2023&&canAutoScore(set2023)?[set2023]:[]),...(set2024&&canAutoScore(set2024)?[set2024]:[]),...(set2025&&canAutoScore(set2025)?[set2025]:[])]}if(grade===11){const original=seniorOriginalSet(11,section),set2022=section==="reading"?grade11Reading2022Verified:section==="use-of-english"?grade11UseOfEnglish2022Verified:null,set2024=grade11Registry[2024][section as keyof typeof grade11Registry[2024]] as QuestionSet|undefined;return[...(original?[original]:[]),...(set2022&&canAutoScore(set2022)?[set2022]:[]),...(set2024&&canAutoScore(set2024)?[set2024]:[])]}return[]},[grade,grade9,juniorSets,section]);
 const listeningGroups=useMemo(()=>section==="listening"?(grade>=9?[...validatedListeningGroupsForGrade(grade),...listeningGroupsFromSets(sets,grade).filter(group=>group.year===2025&&group.source==="official-vsosh-vzlet"&&group.audioSrc?.startsWith("https://reg.storage.yandexcloud.net/public/olymp_tasks/audio_"))]:listeningGroupsFromSets(sets,grade)):[],[grade,section,sets]),bank=useMemo(()=>section==="listening"?listeningGroups.flatMap(group=>group.questions):selectableQuestions(sets,section),[listeningGroups,sets,section]),makeSet=useCallback((session:StandaloneSession)=>{if(section==="listening"){const group=resolveStandaloneListeningGroup(session,listeningGroups);return group?listeningSet(group,session.id):null}const questions=resolveStandaloneQuestions(session,bank),owner=sets.find(set=>set.items.some(item=>item.id===questions[0]?.id))||sets[0];return owner?{...owner,id:session.id,title:sectionName[section],instruction:`Выполни задания: ${sectionName[section]}.`,items:questions}:null},[bank,listeningGroups,section,sets]);
 const begin=useCallback(async()=>{const{data:{session:authSession}}=await createClient().auth.getSession(),studentId=authSession?.user.id||"local-student",history=read<StandaloneHistory>(standaloneHistoryKey(grade,section),{}),last=read<string[]>(standaloneLastKey(grade,section),[]),created=section==="listening"?createStandaloneListeningSession(studentId,grade,listeningGroups,history,last[0]):createStandaloneSession(studentId,grade,section,bank,history,last);if(!created)return;const runtimeSet=makeSet(created.session);if(!runtimeSet)return;localStorage.setItem(standaloneActiveKey(grade,section),JSON.stringify(created.session));setActive({session:created.session,set:runtimeSet})},[bank,grade,listeningGroups,makeSet,section]);
 useEffect(()=>{const stored=read<StandaloneSession|null>(standaloneActiveKey(grade,section),null),runtimeSet=isResumableStandaloneSession(stored,grade,section)?makeSet(stored):null;if(stored&&runtimeSet)setActive({session:stored,set:runtimeSet});setReady(true)},[grade,makeSet,section]);
 useEffect(()=>{const complete=(event:Event)=>{const detail=(event as CustomEvent<{attemptId:string;answers:Record<string,string>}>).detail;if(!active||detail.attemptId!==active.session.id)return;localStorage.setItem(standaloneActiveKey(grade,section),JSON.stringify({...active.session,status:"completed"}));const history=completeStandaloneHistory(read(standaloneHistoryKey(grade,section),{}),active.set.items,detail.answers);localStorage.setItem(standaloneHistoryKey(grade,section),JSON.stringify(history));localStorage.setItem(standaloneLastKey(grade,section),JSON.stringify(section==="listening"?[active.session.listeningGroupId]:active.session.questionIds));localStorage.removeItem(standaloneActiveKey(grade,section))},next=()=>{localStorage.removeItem(standaloneActiveKey(grade,section));setActive(null);void begin()};window.addEventListener("standalone-attempt-completed",complete);window.addEventListener("standalone-new-attempt",next);return()=>{window.removeEventListener("standalone-attempt-completed",complete);window.removeEventListener("standalone-new-attempt",next)}},[active,begin,grade,section]);
 if(!ready)return null;if(active)return <OfficialSection set={active.set}/>;
 if(bank.length){const groupCount=new Set(bank.map(question=>question.groupId||(section==="listening"?`${question.source}-${question.year}-audio`:question.id))).size;return <main className="portal training adaptive-page"><AppHeader blue/><div className="training-variant-shell"><Link href="/training"><ArrowLeft/> Режимы</Link><header><span>OLYMPIC ENGLISH LAB</span><h1>Выбери тренировку</h1><p>Новая попытка сначала использует ещё не выполненные задания</p></header><div className="training-variant-grid"><article><div className="training-variant-icon">{sectionIcon(section)}</div><small>НОВАЯ ПОПЫТКА</small><h2>{sectionName[section]}</h2><p>{grade} класс</p><strong>{Math.min(10,bank.length)}+ заданий</strong><span>{groupCount} доступных групп</span><button type="button" onClick={()=>void begin()}>Начать <Play/></button></article></div></div></main>}
 return <main className="portal training"><AppHeader blue/><div className="adaptive-shell"><Link href="/dashboard"><ArrowLeft/> Главная</Link><section className="adaptive-empty"><BookOpen/><h1>{section==="listening"?"Listening для этого класса временно недоступен. Выберите другой раздел тренировки.":`Проверяемый банк для ${profile.grade} класса пока недоступен.`}</h1></section></div></main>
}

function listeningSet(group:ListeningGroup,attemptId:string):QuestionSet{return{id:attemptId,title:"Listening",section:"listening",instruction:group.instruction,items:group.questions,audioSrc:group.audioSrc,script:group.script,audioMode:group.audioMode}}
