"use client";
import Link from "next/link";
import {ArrowLeft,BookOpen,CheckCircle2,Save} from "lucide-react";
import {useEffect,useRef,useState,useSyncExternalStore} from "react";
import {AppHeader} from "@/components/Brand";
import Sidebar from "@/components/Sidebar";
import {useProfile} from "@/components/ProfileBadge";
import {writingSet} from "@/data/questions/grade-7-8/2022";
import type {QuestionSet} from "@/data/questions/types";
import {saveWritingSubmission,writingSubmissionKey,type WritingSubmissionMarker} from "@/lib/supabase/writing-sync";
import {createClient} from "@/lib/supabase/client";

const countWords=(text:string)=>text.trim()?text.trim().split(/\s+/).length:0;
export const hasWritingHeadline=(text:string)=>{const first=text.split(/\r?\n/).map(line=>line.trim()).find(Boolean)||"";return first.length>=3&&first.split(/\s+/).length<=12};
export const hasRequiredWritingOpening=(text:string,requiredOpening?:string)=>{if(!requiredOpening)return true;const lines=text.split(/\r?\n/).map(line=>line.trim()).filter(Boolean);return !!(lines[0]?.startsWith(requiredOpening)||(hasWritingHeadline(text)&&lines[1]?.startsWith(requiredOpening)))};

export default function WritingSection({set=writingSet}:{set?:QuestionSet}){
 const task=set.items[0],profile=useProfile(),storageKey=`olympic-writing-draft-v2-${task.id}`,submissionKey=writingSubmissionKey(task.id);
 const text=useSyncExternalStore(callback=>{window.addEventListener("writing-autosave",callback);return()=>window.removeEventListener("writing-autosave",callback)},()=>localStorage.getItem(storageKey)||"",()=>"");
 const submissionRaw=useSyncExternalStore(callback=>{window.addEventListener("training-progress",callback);return()=>window.removeEventListener("training-progress",callback)},()=>localStorage.getItem(submissionKey)||"null",()=>"null"),submitted=JSON.parse(submissionRaw) as WritingSubmissionMarker|null,submittedAttemptId=submitted?.attemptId;
 const [confirming,setConfirming]=useState(false),[submitting,setSubmitting]=useState(false),[error,setError]=useState(""),[showWork,setShowWork]=useState(false),[review,setReview]=useState<{score:number;max_score:number;teacher_comment:string|null;status:string}|null>(null);
 const attemptIdRef=useRef(""),startedAtRef=useRef("");
 function update(value:string){if(!startedAtRef.current)startedAtRef.current=new Date().toISOString();localStorage.setItem(storageKey,value);window.dispatchEvent(new Event("writing-autosave"))}
 const words=countWords(text),opening=hasRequiredWritingOpening(text,task.requiredOpening),inLimit=!!task.wordLimit&&words>=task.wordLimit.min&&words<=task.wordLimit.max,headlinePresent=hasWritingHeadline(text);
 useEffect(()=>{if(!submittedAttemptId)return;let active=true;createClient().from("writing_reviews").select("score,max_score,teacher_comment,status").eq("attempt_id",submittedAttemptId).maybeSingle().then(({data})=>{if(active&&data)setReview(data)});return()=>{active=false}},[submittedAttemptId]);
 async function submit(){if(submitting||submitted)return;setSubmitting(true);setError("");const pendingIdKey=`${submissionKey}-attempt-id`;if(!attemptIdRef.current){attemptIdRef.current=localStorage.getItem(pendingIdKey)||crypto.randomUUID();localStorage.setItem(pendingIdKey,attemptIdRef.current)}const completedAt=new Date().toISOString(),result=await saveWritingSubmission({attemptId:attemptIdRef.current,startedAt:startedAtRef.current||completedAt,completedAt,task,text,wordCount:words,headlinePresent});setSubmitting(false);if(result.status==="error"){setError(result.error||"Не удалось сохранить работу");return}setConfirming(false);window.dispatchEvent(new Event("training-progress"))}
 if(submitted)return <main className="portal training"><AppHeader blue/><div className="adaptive-result writing-result"><section><span>{profile.firstName} {profile.lastName}</span><h1>Работа отправлена</h1><p>{profile.grade} класс · Writing · Official {task.year}</p><strong>{submitted.wordCount} слов</strong><div className="writing-review-status"><b>Статус</b><span>{review?.status==="reviewed"?"Проверено":"Ожидает проверки"}</span></div>{review?.status==="reviewed"?<><strong>{review.score} / {review.max_score} · {Math.round(review.score/review.max_score*100)}%</strong>{review.teacher_comment&&<p>Комментарий учителя: {review.teacher_comment}</p>}</>:<p>Итоговая оценка будет выставлена после проверки.</p>}<h2>Формальные требования</h2><ul><li>{inLimit?"✓":"○"} Объём {task.wordLimit?.min}–{task.wordLimit?.max} слов</li><li>{headlinePresent?"✓":"○"} Заголовок обнаружен</li><li>○ Содержательные требования проверит эксперт</li></ul>{showWork&&<article className="writing-submitted-text">{text}</article>}<div><Link href="/dashboard" className="primary blue">На главную</Link><button type="button" onClick={()=>setShowWork(value=>!value)}>{showWork?"Скрыть работу":"Посмотреть свою работу"}</button></div></section></div></main>;
 return <main className="portal training"><AppHeader blue/><div className="training-grid writing-grid"><Sidebar active="Writing"/><section className="lesson"><div className="lesson-top"><Link href="/dashboard"><ArrowLeft/> назад</Link><b>Writing</b><span>{task.grade} класс · {task.year}</span></div><div className="instruction"><span><BookOpen/></span><div><h1>{task.instruction}</h1><p>Официальный муниципальный этап ВсОШ · {task.year}</p></div></div><section className="writing-task"><div className="writing-ad"><span>Writing task</span><p>{task.text}</p>{task.requiredOpening&&<><b>Your text must begin with:</b><blockquote>{task.requiredOpening}</blockquote></>}</div><h2>Требования задания</h2><ul>{task.requirements?.map(requirement=><li key={requirement}><CheckCircle2/>{requirement}</li>)}</ul><textarea value={text} onChange={event=>update(event.target.value)} placeholder="Write your text here…" aria-label="Текст письменной работы"/><div className="writing-status"><span className={inLimit?"ok":""}>{words} слов · требуется {task.wordLimit?.min}–{task.wordLimit?.max}</span>{task.requiredOpening&&<span className={opening?"ok":""}>{opening?"✓":"○"} Обязательная стартовая фраза</span>}<span><Save/> Автосохранение включено</span></div><p className="writing-note">Итоговая оценка не выставляется автоматически: работа требует экспертной проверки.</p>{!inLimit&&<p className="writing-warning">Объём работы не соответствует требованиям: {task.wordLimit?.min}–{task.wordLimit?.max} слов.</p>}{error&&<p className="writing-warning">Ошибка сохранения: {error}</p>}<button type="button" className="finish writing-submit" onClick={()=>setConfirming(true)} disabled={!text.trim()||submitting}>{submitting?"Отправка…":"Сдать работу"}</button>{confirming&&<div className="writing-confirm" role="dialog" aria-modal="true" aria-label="Подтверждение отправки"><div><h2>Отправить работу на проверку?</h2><p>После отправки текст будет сохранён как завершённая работа.</p>{!inLimit&&<p className="writing-warning">Объём работы не соответствует требованиям: {task.wordLimit?.min}–{task.wordLimit?.max} слов. Можно вернуться к редактированию или всё равно отправить.</p>}<footer><button type="button" onClick={()=>setConfirming(false)}>Отмена</button><button type="button" className="primary blue" onClick={submit} disabled={submitting}>Отправить</button></footer></div></div>}</section></section></div></main>;
}
