import test from "node:test";
import assert from "node:assert/strict";
import { grade9OriginalQuestionBank } from "../data/questions/grade-9/original/index.ts";
import { getWeakSubskills, selectSession, weakAreas, type QuestionHistory } from "../lib/adaptive-training.ts";
import { confirmationCandidatesFromStats } from "../lib/supabase/confirmation-candidates.ts";

const now="2026-01-01T00:00:00.000Z";
const rows=(accuracy:number)=>[{subskill:"Reported speech",attempts:2,accuracy,updated_at:now}];
test("attempts 2 and accuracy 0 is a confirmation candidate",()=>assert.equal(confirmationCandidatesFromStats(rows(0)).length,1));
test("attempts 2 and accuracy 50 is a confirmation candidate",()=>assert.equal(confirmationCandidatesFromStats(rows(50)).length,1));
test("attempts 2 and accuracy 100 is not a confirmation candidate",()=>assert.equal(confirmationCandidatesFromStats(rows(100)).length,0));
test("attempts 3 and accuracy 60 is weak",()=>{const history:QuestionHistory={a:{seen:3,attempts:3,correct:1,incorrect:2,lastAttempt:now,skill:"Use of English",subskill:"Reported speech"}};assert.equal(weakAreas(history).length,1)});
test("attempts 3 and accuracy 80 is not weak",()=>{const history:QuestionHistory={a:{seen:5,attempts:5,correct:4,incorrect:1,lastAttempt:now,skill:"Use of English",subskill:"Reported speech"}};assert.equal(weakAreas(history).length,0)});
test("confirmation selection uses another question id in the same subskill",()=>{const same=grade9OriginalQuestionBank.filter(q=>q.subskill==="Reported speech");assert.ok(same.length>=2);const history:QuestionHistory={[same[0].id]:{seen:2,attempts:2,correct:0,incorrect:2,lastAttempt:now,skill:same[0].skill,subskill:same[0].subskill}};const selected=selectSession(grade9OriginalQuestionBank,"quick",10,history,[same[0].id],undefined,()=>.42,[{subskill:"Reported speech",accuracy:0,updatedAt:now}]);assert.ok(selected.some(q=>q.subskill==="Reported speech"&&q.id!==same[0].id));assert.ok(!selected.some(q=>q.id===same[0].id))});
test("Reported speech attempts 2 forces an unseen Reported speech question into Quick",()=>{const same=grade9OriginalQuestionBank.filter(q=>q.subskill==="Reported speech");const history:QuestionHistory=Object.fromEntries(same.slice(0,2).map(q=>[q.id,{seen:1,attempts:1,correct:0,incorrect:1,lastAttempt:now,skill:q.skill,subskill:q.subskill}]));const seen=new Set(Object.keys(history));const selected=selectSession(grade9OriginalQuestionBank,"quick",10,history,[...seen],undefined,()=>.42,[{subskill:"Reported speech",accuracy:0,updatedAt:now}]);assert.ok(selected.some(q=>q.subskill==="Reported speech"&&!seen.has(q.id)))});
test("grade 9 confirmation training never contains grade 7-8",()=>{const selected=selectSession(grade9OriginalQuestionBank,"quick",10,{},[],undefined,()=>.42,[{subskill:"Conditionals",accuracy:50,updatedAt:now}]);assert.ok(selected.every(q=>q.grade===9))});
test("Dashboard and adaptive selector choose the same primary weak subskill",()=>{const stats=[{name:"Word formation",attempts:3,accuracy:50},{name:"Reported speech",attempts:4,accuracy:0}];const dashboardPrimary=getWeakSubskills(stats)[0];const adaptivePrimary=getWeakSubskills(stats)[0];assert.equal(dashboardPrimary.name,"Reported speech");assert.equal(adaptivePrimary.name,dashboardPrimary.name)});
test("five-question adaptive round focuses on primary Reported speech weakness",()=>{const stats=[{name:"Word formation",attempts:3,accuracy:50},{name:"Reported speech",attempts:4,accuracy:0}],primary=getWeakSubskills(stats)[0];const selected=selectSession(grade9OriginalQuestionBank,"weak",5,{},[],primary.name,()=>.42);assert.equal(selected.length,5);assert.equal(selected.filter(q=>q.subskill==="Reported speech").length,4);assert.ok(selected.every(q=>q.grade===9));assert.deepEqual(selected.map(q=>q.subskill),["Reported speech","Reported speech","Reported speech","Reported speech","Tense contrast"])});
test("weak subskill normalization handles case, hyphen and spaces",()=>{const selected=selectSession(grade9OriginalQuestionBank,"weak",5,{},[],"reported-speech",()=>.42);assert.equal(selected.filter(q=>q.subskill==="Reported speech").length,4)});
