import test from "node:test";
import assert from "node:assert/strict";
import { grade9OriginalQuestionBank } from "../data/questions/grade-9/original/index.ts";
import { grade78Listening2025 } from "../data/questions/grade-7-8/2025/index.ts";
import { aggregateSkillStats, attemptNeedsAnswerInsert, buildAnswerPayloads, buildAttemptPayload, readPending, resultFor, saveCompletedAttempt, storePending, type CompletedAttemptInput } from "../lib/supabase/attempt-sync.ts";

class MemoryStorage { private values=new Map<string,string>();getItem(key:string){return this.values.get(key)??null}setItem(key:string,value:string){this.values.set(key,value)}removeItem(key:string){this.values.delete(key)}}
const questions=grade9OriginalQuestionBank.slice(0,10);
const answers=Object.fromEntries(questions.map((question,index)=>[question.id,index<5?question.acceptedAnswers[0]:"wrong"]));
const input:CompletedAttemptInput={attemptId:"11111111-1111-4111-8111-111111111111",startedAt:"2026-01-01T10:00:00.000Z",completedAt:"2026-01-01T10:05:00.000Z",mode:"quick",grade:9,questions,answers,weakSubskill:null};

test("five correct answers out of ten produce 50 percent",()=>assert.deepEqual(resultFor(input),{correct:5,incorrect:5,max:10,percentage:50}));
test("attempt payload uses authenticated student id and stable attempt id",()=>{const payload=buildAttemptPayload(input,"auth-user-id");assert.equal(payload.student_id,"auth-user-id");assert.equal(payload.id,input.attemptId);assert.equal(payload.score,5);assert.equal(payload.max_score,10);assert.equal(payload.percentage,50)});
test("ten questions produce ten answer payloads",()=>{const payloads=buildAnswerPayloads(input,"auth-user-id");assert.equal(payloads.length,10);assert.ok(payloads.every(row=>row.attempt_id===input.attemptId&&row.student_id==="auth-user-id"))});
test("pending retry keeps the same id and does not duplicate the attempt",()=>{const storage=new MemoryStorage();storePending(storage,input);storePending(storage,input);const pending=readPending(storage);assert.equal(pending.length,1);assert.equal(pending[0].attemptId,input.attemptId)});
test("cloud session error stores pending sync",async()=>{const storage=new MemoryStorage();const supabase={auth:{getSession:async()=>({data:{session:null},error:new Error("session unavailable")})}};const result=await saveCompletedAttempt(input,{supabase:supabase as never,storage});assert.equal(result.status,"pending");assert.equal(readPending(storage)[0].attemptId,input.attemptId)});
test("a confirmation answer advances Reported speech attempts from two to three",()=>{const rows=aggregateSkillStats([{skill:"Use of English",subskill:"Reported speech",is_correct:false},{skill:"Use of English",subskill:"Reported speech",is_correct:false},{skill:"Use of English",subskill:"Reported speech",is_correct:true}],"student-id");assert.equal(rows[0].attempts,3);assert.equal(rows[0].correct,1);assert.equal(rows[0].accuracy,33)});
test("adaptive payload uses canonical mode and primary weak metadata",()=>{const reported=grade9OriginalQuestionBank.filter(q=>q.subskill==="Reported speech"),related=grade9OriginalQuestionBank.find(q=>q.subskill==="Tense contrast")!;const adaptive:CompletedAttemptInput={...input,mode:"weak",questions:[...reported,related],answers:{},weakSubskill:"Reported speech"};const payload=buildAttemptPayload(adaptive,"student-id");assert.equal(payload.mode,"adaptive");assert.equal(payload.total_questions,5);assert.deepEqual(payload.metadata,{grade:9,primaryWeakSubskill:"Reported speech"});assert.equal(buildAnswerPayloads(adaptive,"student-id").length,5)});
test("adaptive aggregation adds four Reported speech answers and keeps the related subskill separate",()=>{const rows=aggregateSkillStats([{skill:"Use of English",subskill:"Reported speech",is_correct:false},{skill:"Use of English",subskill:"Reported speech",is_correct:false},...Array.from({length:3},()=>({skill:"Use of English",subskill:"Reported speech",is_correct:true})),{skill:"Use of English",subskill:"Reported speech",is_correct:false},{skill:"Use of English",subskill:"Tense contrast",is_correct:true}],"student-id");const reported=rows.find(row=>row.subskill==="Reported speech")!,related=rows.find(row=>row.subskill==="Tense contrast")!;assert.deepEqual({attempts:reported.attempts,correct:reported.correct,incorrect:reported.incorrect,accuracy:reported.accuracy},{attempts:6,correct:3,incorrect:3,accuracy:50});assert.deepEqual({attempts:related.attempts,correct:related.correct},{attempts:1,correct:1})});
test("stable attempt id prevents a second answer insert",()=>{assert.equal(attemptNeedsAnswerInsert([]),true);assert.equal(attemptNeedsAnswerInsert([{id:"existing-answer"}]),false)});

test("cloud attempt scoring accepts official upper-case keys case-insensitively",()=>{const question=grade78Listening2025.items[0] as unknown as typeof questions[number],official:CompletedAttemptInput={...input,questions:[question],answers:{[question.id]:"f"},grade:7};assert.equal(resultFor(official).correct,1);assert.equal(buildAnswerPayloads(official,"student-id")[0].is_correct,true)});
test("manual-review answers do not pollute weak-area statistics",()=>{const rows=aggregateSkillStats([{skill:"Writing",subskill:"extended writing",is_correct:null},{skill:"Reading",subskill:"detail",is_correct:false},{skill:"Reading",subskill:"detail",is_correct:true}],"student-id");assert.equal(rows.some(row=>row.skill==="Writing"),false);assert.deepEqual(rows.find(row=>row.skill==="Reading"),{student_id:"student-id",skill:"Reading",subskill:"detail",attempts:2,correct:1,incorrect:1,accuracy:50})});
