import test from"node:test";import assert from"node:assert/strict";import{existsSync,readFileSync}from"node:fs";import{checkAnswer}from"../lib/answer-checker.ts";import{createFullSession,FULL_SECTION_ORDER,fullBankForGrade,nextFullSectionIndex,resolveFullListeningGroup,resolveSessionQuestions,scoreFullObjectiveSections,buildFullQuestionReviews,selectFullQuestions,type FullQuestion}from"../lib/full-olympiad.ts";
test("full olympiad keeps the required four-section order and skips only missing Listening",()=>{assert.deepEqual(FULL_SECTION_ORDER,["listening","reading","use-of-english","writing"]);const grade9=createFullSession(9,{},[],()=>.5,"2026-01-01T00:00:00.000Z");assert.equal(FULL_SECTION_ORDER[grade9.sectionIndex],"reading");assert.equal(grade9.listeningGroupId,undefined);assert.deepEqual(grade9.questionIds.listening,[]);assert.equal(resolveFullListeningGroup(grade9),null);assert.ok(resolveSessionQuestions(grade9).every(question=>question.section!=="listening"));assert.equal(nextFullSectionIndex(grade9),2);for(const grade of[10,11]as const){const session=createFullSession(grade,{},[],()=>.5,"2026-01-01T00:00:00.000Z");assert.equal(FULL_SECTION_ORDER[session.sectionIndex],"listening");assert.equal(session.listeningGroupId,"g"+grade+"-2022-listening");assert.equal(session.questionIds.listening.length,20);assert.equal(resolveFullListeningGroup(session)?.id,"g"+grade+"-2022-listening");assert.ok(resolveSessionQuestions(session).some(question=>question.section==="listening"));assert.equal(nextFullSectionIndex(session),1)}});
test("full bank uses only auto-checkable objective questions and preserves metadata",()=>{for(const grade of[7,8,9,10,11]){const{objective,writing}=fullBankForGrade(grade);assert.ok(objective.length);assert.ok(writing.type==="writing");assert.ok(objective.every(q=>q.acceptedAnswers.length&&!q.needsReview&&q.source&&q.id&&q.section&&q.skill&&q.subskill))}});
test("junior full olympiad starts with the shared Grade 7-8 Listening group",()=>{const audioPath="public/audio/grade-7-8/2022/listening.mp3";assert.ok(existsSync(audioPath));const audio=readFileSync(audioPath);assert.ok(audio.length>1_000_000);assert.equal(audio.subarray(0,80).toString("utf8").startsWith("version https://git-lfs.github.com/spec/v1"),false);for(const grade of[7,8]){const bank=fullBankForGrade(grade),group=bank.listeningGroups[0];assert.deepEqual(bank.listeningGroups.map(group=>group.id),["vsosh-7-8-2022-listening"]);assert.equal(group.audioSrc,"/audio/grade-7-8/2022/listening.mp3");assert.equal(group.audioMode,"file");const session=createFullSession(grade,{},[],()=>.5,"2026-01-01T00:00:00.000Z");assert.equal(session.listeningGroupId,"vsosh-7-8-2022-listening");assert.ok(resolveSessionQuestions(session).some(question=>question.section==="listening"))}});
test("senior full olympiad starts with official validated 2022 Listening",()=>{for(const grade of[10,11]as const){const audioPath="public/audio/grade-"+grade+"/2022/listening.mp3";assert.ok(existsSync(audioPath));const audio=readFileSync(audioPath);assert.ok(audio.length>1_000_000);assert.equal(audio.subarray(0,80).toString("utf8").startsWith("version https://git-lfs.github.com/spec/v1"),false);const bank=fullBankForGrade(grade),group=bank.listeningGroups[0];assert.deepEqual(bank.listeningGroups.map(group=>group.id),["g"+grade+"-2022-listening"]);assert.equal(group.audioSrc,"/audio/grade-"+grade+"/2022/listening.mp3");assert.equal(group.audioMode,"file");assert.equal(group.questions.length,20);assert.ok(group.questions.every(question=>Number(question.grade)===grade));const session=createFullSession(grade,{},[],()=>.5,"2026-01-01T00:00:00.000Z");assert.equal(session.listeningGroupId,"g"+grade+"-2022-listening");assert.ok(resolveSessionQuestions(session).some(question=>question.section==="listening"))}});
test("unseen questions are selected before seen questions",()=>{const mk=(id:string):FullQuestion=>({id,grade:9,year:2024,stage:"municipal",source:"official-vsosh-vzlet",sourceLabel:"x",platformLabel:"x" as FullQuestion["platformLabel"],section:"reading",skill:"Reading",subskill:"detail",difficulty:"medium",type:"gap-fill",instruction:"x",text:id,options:[],acceptedAnswers:["x"],points:1,explanation:"",tags:[],needsReview:false});const selected=selectFullQuestions([mk("seen"),mk("new")],"reading",{seen:{seen:2,incorrect:0}},[],1,()=>.5);assert.equal(selected[0].id,"new")});
test("grouped Reading tasks remain intact",()=>{const bank=fullBankForGrade(9).objective,selected=selectFullQuestions(bank,"reading",{},[],1,()=>.5),group=selected[0].groupId;assert.ok(group);assert.deepEqual(selected.filter(q=>q.groupId===group).map(q=>q.id),bank.filter(q=>q.groupId===group).map(q=>q.id))});
test("Full Olympiad cannot silently use speech-only or cross-grade Listening",()=>{assert.equal(fullBankForGrade(9).listeningGroups.length,0);const grade9=createFullSession(9,{},[],()=>.5,"2026-01-01T00:00:00.000Z");assert.equal(grade9.listeningGroupId,undefined);assert.deepEqual(grade9.questionIds.listening,[]);assert.ok(resolveSessionQuestions(grade9).every(question=>question.section!=="listening"));for(const grade of[10,11]as const){const groups=fullBankForGrade(grade).listeningGroups;assert.equal(groups.length,1);assert.equal(groups[0].grade,grade);assert.equal(groups[0].audioMode,"file");assert.equal(groups[0].audioSrc,"/audio/grade-"+grade+"/2022/listening.mp3");assert.ok(!groups[0].audioSrc?.includes("/grade-9/"));const session=createFullSession(grade,{},[],()=>.5,"2026-01-01T00:00:00.000Z");assert.equal(session.listeningGroupId,"g"+grade+"-2022-listening")}});
test("Reading selection keeps complete groups",()=>{const bank=fullBankForGrade(11).objective,selected=selectFullQuestions(bank,"reading",{},[],1,()=>.5);for(const id of new Set(selected.map(q=>q.groupId||q.id)))assert.deepEqual(selected.filter(q=>(q.groupId||q.id)===id).map(q=>q.id),bank.filter(q=>(q.groupId||q.id)===id).map(q=>q.id))});

test("standalone completion does not require teacher submission",()=>{const source=readFileSync("components/training/FullOlympiadTraining.tsx","utf8");assert.match(source,/studentClass/);assert.ok(source.includes("if(!teacherLinked){setSubmitting(false);finishFullSession(completedAt,\"local\");return}"));assert.ok(source.includes("teacherLinked?\"Завершить и отправить Writing\":\"Завершить тренировку\""));assert.match(source,/Writing сохранён локально/);assert.doesNotMatch(source,/Failed to fetch/)});

test("teacher-linked completion keeps teacher workflow",()=>{const source=readFileSync("components/training/FullOlympiadTraining.tsx","utf8"),localIndex=source.indexOf("if(!teacherLinked)"),saveIndex=source.indexOf("const result=await saveWritingSubmission");assert.ok(localIndex>=0&&saveIndex>localIndex);assert.ok(source.includes("finishFullSession(completedAt,\"pending\")"));assert.match(source,/writing_reviews/)});


test("standalone start clears stale teacher class marker",()=>{const source=readFileSync("app/start/page.tsx","utf8");assert.match(source,/else localStorage\.removeItem\("studentClass"\)/);assert.match(source,/return}localStorage\.removeItem\("studentClass"\)/)});
test("standalone objective result scores Listening Reading and Use of English only",()=>{const q=(id:string,section:FullQuestion["section"],answer:string):FullQuestion=>({id,grade:"7-8",year:2022,stage:"municipal",source:"official-vsosh-vzlet",sourceLabel:"x",platformLabel:"Взлёт",section,skill:section==="use-of-english"?"Use of English":section[0].toUpperCase()+section.slice(1),subskill:"test",difficulty:"medium",type:"gap-fill",instruction:"x",text:id,options:[],acceptedAnswers:[answer],points:1,explanation:"",tags:[],needsReview:false}as FullQuestion),result=scoreFullObjectiveSections([q("l1","listening","a"),q("l2","listening","b"),q("r1","reading","c"),q("u1","use-of-english","d"),q("w1","writing","essay")],{l1:"a",l2:"wrong",r1:"c",u1:"d",w1:"essay"},(question,answer)=>checkAnswer(question,answer)===true);assert.deepEqual(result.rows.map(row=>[row.section,row.correct,row.total]),[["listening",1,2],["reading",1,1],["use-of-english",1,1]]);assert.equal(result.correct,3);assert.equal(result.total,4);assert.equal(result.percentage,75)});

test("standalone without teacher code bypasses Supabase submission and review polling",()=>{const source=readFileSync("components/training/FullOlympiadTraining.tsx","utf8"),localIndex=source.indexOf("if(!teacherLinked)"),saveIndex=source.indexOf("const result=await saveWritingSubmission");assert.ok(localIndex>=0&&saveIndex>localIndex);const localBranch=source.slice(localIndex,saveIndex);assert.match(localBranch,/finishFullSession\(completedAt,"local"\)/);assert.doesNotMatch(localBranch,/saveWritingSubmission|createClient|writing_reviews/);assert.match(source,/session\.writingStatus!=="pending"\|\|!teacherLinked/)});

test("standalone with Writing completes with local unscored Writing status",()=>{const source=readFileSync("components/training/FullOlympiadTraining.tsx","utf8");assert.match(source,/finishFullSession\(completedAt,"local"\)/);assert.match(source,/Writing будет сохранён локально/);assert.match(source,/Сохранено без оценки/);assert.match(source,/общий процент рассчитан по Listening, Reading и Use of English/)});

test("teacher workflow still submits Writing and waits for review",()=>{const source=readFileSync("components/training/FullOlympiadTraining.tsx","utf8"),localIndex=source.indexOf("if(!teacherLinked)"),saveIndex=source.indexOf("const result=await saveWritingSubmission");assert.ok(localIndex>=0&&saveIndex>localIndex);assert.match(source,/finishFullSession\(completedAt,"pending"\)/);assert.match(source,/writing_reviews/);assert.match(source,/Writing проверит учитель/)});

test("unavailable Supabase cannot block standalone completion",()=>{const source=readFileSync("components/training/FullOlympiadTraining.tsx","utf8"),localIndex=source.indexOf("if(!teacherLinked)"),saveIndex=source.indexOf("const result=await saveWritingSubmission");assert.ok(localIndex>=0&&saveIndex>localIndex);assert.doesNotMatch(source,/Failed to fetch/);const start=readFileSync("app/start/page.tsx","utf8");assert.match(start,/else localStorage\.removeItem\("studentClass"\)/);assert.match(start,/return}localStorage\.removeItem\("studentClass"\)/)});
test("final review explains T F NS Listening answers without invented evidence",()=>{const mk=(id:string,text:string,answer:string):FullQuestion=>({id,grade:"7-8",year:2022,stage:"municipal",source:"official-vsosh-vzlet",sourceLabel:"x",platformLabel:"Взлёт",section:"listening",skill:"Listening",subskill:"detail comprehension",difficulty:"medium",type:"true-false",instruction:"x",text,options:["T","F","NS"],acceptedAnswers:[answer],points:1,explanation:"",tags:[],needsReview:false}as FullQuestion),reviews=buildFullQuestionReviews([mk("l1","The speaker likes the plan.","t"),mk("l2","The speaker arrived early.","f"),mk("l3","The speaker names the price.","ns")],{l1:"f",l2:"t",l3:"t"},(q,a)=>checkAnswer(q,a)===true,{listeningScript:"The speaker says the plan is useful. She arrived late."});assert.match(reviews[0].rule,/True/);assert.match(reviews[1].rule,/False/);assert.match(reviews[2].rule,/Not Stated/);assert.equal(reviews[2].evidence,undefined)});

const reviewQuestion=(overrides:Partial<FullQuestion>):FullQuestion=>({id:"q",grade:"7-8",year:2022,stage:"municipal",source:"official-vsosh-vzlet",sourceLabel:"x",platformLabel:"Взлёт",section:"use-of-english",skill:"Use of English",subskill:"Grammar",difficulty:"medium",type:"multiple-choice",instruction:"x",text:"x",options:[],acceptedAnswers:["a"],points:1,explanation:"",tags:[],needsReview:false,...overrides} as FullQuestion);
const reviewFor=(question:FullQuestion,answer:string)=>buildFullQuestionReviews([question],{[question.id]:answer},(q,a)=>checkAnswer(q,a)===true)[0];
const noGeneric=(text:string)=>{assert.doesNotMatch(text,/соответствует ключу|вариант не подтверждается текстом|подходит по грамматической форме/i)};

test("final review explains Reading choices with concrete option meaning and evidence",()=>{const question=reviewQuestion({id:"r1",section:"reading",skill:"Reading",subskill:"Detail",text:"What doubled within a year?",options:["A Book loans","B Total visits","C Storage rooms"],acceptedAnswers:["b"],passage:"Book loans did not immediately rise. Total visits doubled within a year. Staff added workshops."}),review=reviewFor(question,"a");assert.equal(review.userAnswer,"A — Book loans");assert.equal(review.correctAnswer,"B — Total visits");assert.match(review.mistakeReason,/Book loans/);assert.match(review.mistakeReason,/Total visits/);assert.match(review.correctReason,/Total visits/);assert.match(review.evidence||"",/Total visits doubled/);assert.doesNotMatch(review.correctReason,/evidence.*не найдено/i);noGeneric(review.mistakeReason);noGeneric(review.correctReason)});

test("final review explains CONSIST to inconsistency word formation precisely",()=>{const question=reviewQuestion({id:"u1",subskill:"Word formation",type:"gap-fill",text:"The reconstruction revealed a serious ___. (CONSIST)",options:[],acceptedAnswers:["inconsistency"]}),review=reviewFor(question,"consistent");assert.match(review.rule,/CONSIST → inconsistency/);assert.match(review.rule,/Исходное слово CONSIST: глагол/);assert.match(review.rule,/требуется существительное/);assert.match(review.rule,/префикс in-|суффикс -ency/);assert.match(review.mistakeReason,/consistent — прилагательное/);assert.match(review.correctReason,/inconsistency/);assert.match(review.correctReason,/отрицательный префикс in-|суффикс -ency/);noGeneric(review.mistakeReason);noGeneric(review.correctReason)});

test("final review explains reference questions",()=>{const question=reviewQuestion({id:"u2",subskill:"Reference",text:"In the phrase 'the latter', what does it refer to?",options:["A the first idea","B the second idea"],acceptedAnswers:["b"]}),review=reviewFor(question,"a");assert.match(review.rule,/latter.*второй/i);assert.match(review.mistakeReason,/reference word/);assert.match(review.correctReason,/reference word/)});

test("final review uses a short safe fallback when evidence is missing",()=>{const question=reviewQuestion({id:"r2",section:"reading",skill:"Reading",subskill:"Detail",text:"What is stated?",options:["A one","B two"],acceptedAnswers:["b"]}),review=reviewFor(question,"a");assert.equal(review.evidence,undefined);assert.match(review.mistakeReason,/Правильный ответ: two\. Для этого задания пока нет подробного объяснения\./);assert.match(review.correctReason,/Правильный ответ: two\. Для этого задания пока нет подробного объяснения\./)});

test("final result UI keeps answers hidden until completed review panel and uses Russian labels",()=>{const source=readFileSync("components/training/FullOlympiadTraining.tsx","utf8"),completedIndex=source.indexOf("if(session.completedAt)"),reviewIndex=source.indexOf("FullReviewPanel");assert.ok(completedIndex>=0&&reviewIndex>completedIndex);assert.match(source,/Только ошибки/);assert.match(source,/Все задания/);assert.match(source,/Разобрать ошибки/);assert.match(source,/Задание \{item\.number\}/);assert.doesNotMatch(source,/Question \{item\.number\}/);assert.match(source,/\{item\.userAnswerPrefix\}/);assert.match(source,/\{item\.correctAnswerPrefix\}/);assert.match(source,/Почему это ошибка/);assert.match(source,/Почему правильный ответ подходит/)});

test("final review explains admit plus gerund specifically",()=>{const question=reviewQuestion({id:"u3",text:"She admitted ___ the warning signs.",options:["A to overlook","B overlooking"],acceptedAnswers:["b"]}),review=reviewFor(question,"a");assert.match(review.mistakeReason,/после admit.*gerund/i);assert.match(review.correctReason,/-ing form после admit/i);assert.match(review.rule,/admit.*gerund/i);assert.equal(review.evidence,undefined);noGeneric(review.mistakeReason);noGeneric(review.correctReason)});

test("final review explains cast light on without mixing option key into the explanation",()=>{const question=reviewQuestion({id:"u4",subskill:"Collocations",text:"One interview ___ light on a forgotten protest.",options:["A cast","B made","C put","D set"],acceptedAnswers:["a"],explanation:"Cast light on is fixed."}),review=reviewFor(question,"d");assert.equal(review.userAnswer,"D — set");assert.equal(review.correctAnswer,"A — cast");assert.match(review.mistakeReason,/set.*пролить свет/);assert.match(review.correctReason,/cast light on.*пролить свет/);assert.doesNotMatch(review.correctReason,/A — cast|A cast/);noGeneric(review.mistakeReason);noGeneric(review.correctReason)});

test("final review explains cast doubt on as a collocation",()=>{const question=reviewQuestion({id:"u5",subskill:"Collocations",text:"The experiment ___ doubt on the accepted diagram.",options:["A cast","B did","C raised up","D made"],acceptedAnswers:["a"],explanation:"Cast doubt on is fixed."}),review=reviewFor(question,"b");assert.equal(review.userAnswer,"B — did");assert.equal(review.correctAnswer,"A — cast");assert.match(review.mistakeReason,/did.*поставить под сомнение/);assert.match(review.correctReason,/cast doubt on.*поставить под сомнение/);assert.doesNotMatch(review.correctReason,/A — cast|A cast/);noGeneric(review.mistakeReason);noGeneric(review.correctReason)});

test("final review explains contradictory by meaning in context",()=>{const question=reviewQuestion({id:"u6",subskill:"Lexical choice",text:"The two versions were different but not necessarily ___.",options:["A contradictory","B identical","C obedient","D scarce"],acceptedAnswers:["a"],explanation:"Contradictory captures incompatible accounts."}),review=reviewFor(question,"b");assert.match(review.mistakeReason,/identical означает одинаковый/);assert.match(review.correctReason,/contradictory.*противоречить/i);assert.match(review.rule,/Contradictory.*противоречащий/);noGeneric(review.mistakeReason);noGeneric(review.correctReason)});

test("final review explains not as as parallel contrast",()=>{const question=reviewQuestion({id:"u7",subskill:"Open cloze",type:"open-short-answer",text:"Memory should be treated as evidence, ___ as a perfect record.",options:[],acceptedAnswers:["not"],explanation:"The correlative structure is not as."}),review=reviewFor(question,"as");assert.match(review.mistakeReason,/as evidence.*perfect record/);assert.match(review.correctReason,/as evidence, not as a perfect record/);assert.match(review.correctReason,/Память следует рассматривать как свидетельство/);assert.doesNotMatch(review.correctReason,/correlative structure/i);noGeneric(review.mistakeReason);noGeneric(review.correctReason)});

test("final review explains vocabulary and collocation choices",()=>{const question=reviewQuestion({id:"u8",subskill:"Vocabulary and collocation",text:"Choose the best phrase for the context.",options:["A make a decision","B do a decision"],acceptedAnswers:["a"]}),review=reviewFor(question,"b");assert.match(review.mistakeReason,/decision.*make|make.*decision/);assert.match(review.correctReason,/make a decision.*устойчивое сочетание/);assert.equal(review.evidence,undefined);noGeneric(review.mistakeReason);noGeneric(review.correctReason)});