import test from"node:test";import assert from"node:assert/strict";import{existsSync,readFileSync}from"node:fs";import{checkAnswer}from"../lib/answer-checker.ts";import{createFullSession,FULL_SECTION_ORDER,fullBankForGrade,nextFullSectionIndex,resolveFullListeningGroup,resolveSessionQuestions,scoreFullObjectiveSections,selectFullQuestions,type FullQuestion}from"../lib/full-olympiad.ts";
test("full olympiad keeps the required four-section order and skips only missing Listening",()=>{assert.deepEqual(FULL_SECTION_ORDER,["listening","reading","use-of-english","writing"]);const grade9=createFullSession(9,{},[],()=>.5,"2026-01-01T00:00:00.000Z");assert.equal(FULL_SECTION_ORDER[grade9.sectionIndex],"reading");assert.equal(grade9.listeningGroupId,undefined);assert.deepEqual(grade9.questionIds.listening,[]);assert.equal(resolveFullListeningGroup(grade9),null);assert.ok(resolveSessionQuestions(grade9).every(question=>question.section!=="listening"));assert.equal(nextFullSectionIndex(grade9),2);for(const grade of[10,11]as const){const session=createFullSession(grade,{},[],()=>.5,"2026-01-01T00:00:00.000Z");assert.equal(FULL_SECTION_ORDER[session.sectionIndex],"listening");assert.equal(session.listeningGroupId,"g"+grade+"-2022-listening");assert.equal(session.questionIds.listening.length,20);assert.equal(resolveFullListeningGroup(session)?.id,"g"+grade+"-2022-listening");assert.ok(resolveSessionQuestions(session).some(question=>question.section==="listening"));assert.equal(nextFullSectionIndex(session),1)}});
test("full bank uses only auto-checkable objective questions and preserves metadata",()=>{for(const grade of[7,8,9,10,11]){const{objective,writing}=fullBankForGrade(grade);assert.ok(objective.length);assert.ok(writing.type==="writing");assert.ok(objective.every(q=>q.acceptedAnswers.length&&!q.needsReview&&q.source&&q.id&&q.section&&q.skill&&q.subskill))}});
test("junior full olympiad starts with the shared Grade 7-8 Listening group",()=>{const audioPath="public/audio/grade-7-8/2022/listening.mp3";assert.ok(existsSync(audioPath));const audio=readFileSync(audioPath);assert.ok(audio.length>1_000_000);assert.equal(audio.subarray(0,80).toString("utf8").startsWith("version https://git-lfs.github.com/spec/v1"),false);for(const grade of[7,8]){const bank=fullBankForGrade(grade),group=bank.listeningGroups[0];assert.deepEqual(bank.listeningGroups.map(group=>group.id),["vsosh-7-8-2022-listening"]);assert.equal(group.audioSrc,"/audio/grade-7-8/2022/listening.mp3");assert.equal(group.audioMode,"file");const session=createFullSession(grade,{},[],()=>.5,"2026-01-01T00:00:00.000Z");assert.equal(session.listeningGroupId,"vsosh-7-8-2022-listening");assert.ok(resolveSessionQuestions(session).some(question=>question.section==="listening"))}});
test("senior full olympiad starts with official validated 2022 Listening",()=>{for(const grade of[10,11]as const){const audioPath="public/audio/grade-"+grade+"/2022/listening.mp3";assert.ok(existsSync(audioPath));const audio=readFileSync(audioPath);assert.ok(audio.length>1_000_000);assert.equal(audio.subarray(0,80).toString("utf8").startsWith("version https://git-lfs.github.com/spec/v1"),false);const bank=fullBankForGrade(grade),group=bank.listeningGroups[0];assert.deepEqual(bank.listeningGroups.map(group=>group.id),["g"+grade+"-2022-listening"]);assert.equal(group.audioSrc,"/audio/grade-"+grade+"/2022/listening.mp3");assert.equal(group.audioMode,"file");assert.equal(group.questions.length,20);assert.ok(group.questions.every(question=>Number(question.grade)===grade));const session=createFullSession(grade,{},[],()=>.5,"2026-01-01T00:00:00.000Z");assert.equal(session.listeningGroupId,"g"+grade+"-2022-listening");assert.ok(resolveSessionQuestions(session).some(question=>question.section==="listening"))}});
test("unseen questions are selected before seen questions",()=>{const mk=(id:string):FullQuestion=>({id,grade:9,year:2024,stage:"municipal",source:"official-vsosh-vzlet",sourceLabel:"x",platformLabel:"x" as FullQuestion["platformLabel"],section:"reading",skill:"Reading",subskill:"detail",difficulty:"medium",type:"gap-fill",instruction:"x",text:id,options:[],acceptedAnswers:["x"],points:1,explanation:"",tags:[],needsReview:false});const selected=selectFullQuestions([mk("seen"),mk("new")],"reading",{seen:{seen:2,incorrect:0}},[],1,()=>.5);assert.equal(selected[0].id,"new")});
test("grouped Reading tasks remain intact",()=>{const bank=fullBankForGrade(9).objective,selected=selectFullQuestions(bank,"reading",{},[],1,()=>.5),group=selected[0].groupId;assert.ok(group);assert.deepEqual(selected.filter(q=>q.groupId===group).map(q=>q.id),bank.filter(q=>q.groupId===group).map(q=>q.id))});
test("Full Olympiad cannot silently use speech-only or cross-grade Listening",()=>{assert.equal(fullBankForGrade(9).listeningGroups.length,0);const grade9=createFullSession(9,{},[],()=>.5,"2026-01-01T00:00:00.000Z");assert.equal(grade9.listeningGroupId,undefined);assert.deepEqual(grade9.questionIds.listening,[]);assert.ok(resolveSessionQuestions(grade9).every(question=>question.section!=="listening"));for(const grade of[10,11]as const){const groups=fullBankForGrade(grade).listeningGroups;assert.equal(groups.length,1);assert.equal(groups[0].grade,grade);assert.equal(groups[0].audioMode,"file");assert.equal(groups[0].audioSrc,"/audio/grade-"+grade+"/2022/listening.mp3");assert.ok(!groups[0].audioSrc?.includes("/grade-9/"));const session=createFullSession(grade,{},[],()=>.5,"2026-01-01T00:00:00.000Z");assert.equal(session.listeningGroupId,"g"+grade+"-2022-listening")}});
test("Reading selection keeps complete groups",()=>{const bank=fullBankForGrade(11).objective,selected=selectFullQuestions(bank,"reading",{},[],1,()=>.5);for(const id of new Set(selected.map(q=>q.groupId||q.id)))assert.deepEqual(selected.filter(q=>(q.groupId||q.id)===id).map(q=>q.id),bank.filter(q=>(q.groupId||q.id)===id).map(q=>q.id))});

test("standalone completion does not require teacher submission",()=>{const source=readFileSync("components/training/FullOlympiadTraining.tsx","utf8");assert.match(source,/studentClass/);assert.ok(source.includes("if(!teacherLinked){setSubmitting(false);finishFullSession(completedAt,\"local\");return}"));assert.ok(source.includes("teacherLinked?\"Завершить и отправить Writing\":\"Завершить тренировку\""));assert.match(source,/Writing сохранён локально/);assert.doesNotMatch(source,/Failed to fetch/)});

test("teacher-linked completion keeps teacher workflow",()=>{const source=readFileSync("components/training/FullOlympiadTraining.tsx","utf8"),localIndex=source.indexOf("if(!teacherLinked)"),saveIndex=source.indexOf("const result=await saveWritingSubmission");assert.ok(localIndex>=0&&saveIndex>localIndex);assert.ok(source.includes("finishFullSession(completedAt,\"pending\")"));assert.match(source,/writing_reviews/)});


test("standalone start clears stale teacher class marker",()=>{const source=readFileSync("app/start/page.tsx","utf8");assert.match(source,/else localStorage\.removeItem\("studentClass"\)/);assert.match(source,/return}localStorage\.removeItem\("studentClass"\)/)});
test("standalone objective result scores Listening Reading and Use of English only",()=>{const q=(id:string,section:FullQuestion["section"],answer:string):FullQuestion=>({id,grade:"7-8",year:2022,stage:"municipal",source:"official-vsosh-vzlet",sourceLabel:"x",platformLabel:"Взлёт",section,skill:section==="use-of-english"?"Use of English":section[0].toUpperCase()+section.slice(1),subskill:"test",difficulty:"medium",type:"gap-fill",instruction:"x",text:id,options:[],acceptedAnswers:[answer],points:1,explanation:"",tags:[],needsReview:false}as FullQuestion),result=scoreFullObjectiveSections([q("l1","listening","a"),q("l2","listening","b"),q("r1","reading","c"),q("u1","use-of-english","d"),q("w1","writing","essay")],{l1:"a",l2:"wrong",r1:"c",u1:"d",w1:"essay"},(question,answer)=>checkAnswer(question,answer)===true);assert.deepEqual(result.rows.map(row=>[row.section,row.correct,row.total]),[["listening",1,2],["reading",1,1],["use-of-english",1,1]]);assert.equal(result.correct,3);assert.equal(result.total,4);assert.equal(result.percentage,75)});

test("standalone without teacher code bypasses Supabase submission and review polling",()=>{const source=readFileSync("components/training/FullOlympiadTraining.tsx","utf8"),localIndex=source.indexOf("if(!teacherLinked)"),saveIndex=source.indexOf("const result=await saveWritingSubmission");assert.ok(localIndex>=0&&saveIndex>localIndex);const localBranch=source.slice(localIndex,saveIndex);assert.match(localBranch,/finishFullSession\(completedAt,"local"\)/);assert.doesNotMatch(localBranch,/saveWritingSubmission|createClient|writing_reviews/);assert.match(source,/session\.writingStatus!=="pending"\|\|!teacherLinked/)});

test("standalone with Writing completes with local unscored Writing status",()=>{const source=readFileSync("components/training/FullOlympiadTraining.tsx","utf8");assert.match(source,/finishFullSession\(completedAt,"local"\)/);assert.match(source,/Writing будет сохранён локально/);assert.match(source,/Сохранено без оценки/);assert.match(source,/общий процент рассчитан по Listening, Reading и Use of English/)});

test("teacher workflow still submits Writing and waits for review",()=>{const source=readFileSync("components/training/FullOlympiadTraining.tsx","utf8"),localIndex=source.indexOf("if(!teacherLinked)"),saveIndex=source.indexOf("const result=await saveWritingSubmission");assert.ok(localIndex>=0&&saveIndex>localIndex);assert.match(source,/finishFullSession\(completedAt,"pending"\)/);assert.match(source,/writing_reviews/);assert.match(source,/Writing проверит учитель/)});

test("unavailable Supabase cannot block standalone completion",()=>{const source=readFileSync("components/training/FullOlympiadTraining.tsx","utf8"),localIndex=source.indexOf("if(!teacherLinked)"),saveIndex=source.indexOf("const result=await saveWritingSubmission");assert.ok(localIndex>=0&&saveIndex>localIndex);assert.doesNotMatch(source,/Failed to fetch/);const start=readFileSync("app/start/page.tsx","utf8");assert.match(start,/else localStorage\.removeItem\("studentClass"\)/);assert.match(start,/return}localStorage\.removeItem\("studentClass"\)/)});