import test from"node:test";import assert from"node:assert/strict";import{existsSync,readFileSync,statSync}from"node:fs";import{adaptiveBankForSeniorGrade,grade10Listening2022,grade10Official2024,grade10WritingSets,grade11Listening2022,grade11Registry,grade11WritingSets,objectiveBankForSeniorGrade,seniorOriginalReading,seniorOriginalSet,seniorOriginalUseOfEnglish}from"../data/questions/grade-10-11/index.ts";import{originalWritingSets}from"../data/questions/writing-original.ts";import type{QuestionSet,Section}from"../data/questions/types.ts";import{createFullSession,FULL_SECTION_ORDER,fullBankForGrade,resolveSessionQuestions}from"../lib/full-olympiad.ts";import{completeStandaloneHistory,createStandaloneListeningSession,createStandaloneSession,listeningGroupsFromSets,selectableQuestions}from"../lib/standalone-training.ts";import{isQuestionAllowedForGrade,registryForGrade}from"../lib/training-grade.ts";
import{disabledListeningGroups,isStrictlySafeListeningGroup,validatedListeningGroupsForGrade}from"../lib/listening-registry.ts";
test("grade 10 and 11 registries are isolated",()=>{assert.equal(registryForGrade(10),"grade-10");assert.equal(registryForGrade(11),"grade-11");for(const grade of[10,11]as const){const bank=objectiveBankForSeniorGrade(grade);assert.ok(bank.length>=60);assert.ok(bank.every(q=>q.grade===grade&&isQuestionAllowedForGrade(q,grade)));assert.ok(bank.every(q=>!isQuestionAllowedForGrade(q,grade===10?11:10)));assert.ok(bank.every(q=>!isQuestionAllowedForGrade(q,9)))}});
test("only verified keyed senior objective items are auto-scored",()=>{for(const grade of[10,11]as const)assert.ok(objectiveBankForSeniorGrade(grade).every(q=>q.year===2024&&q.acceptedAnswers.length&&!q.needsReview))});
test("senior Reading groups stay indivisible and ordered",()=>{for(const grade of[10,11]as const){const reading=objectiveBankForSeniorGrade(grade).filter(q=>q.section==="reading");for(const group of new Set(reading.map(q=>q.groupId)))assert.deepEqual(reading.filter(q=>q.groupId===group).map(q=>q.id),objectiveBankForSeniorGrade(grade).filter(q=>q.groupId===group).map(q=>q.id))}});

test("full olympiad skips unavailable Grade 9 Listening and starts validated senior Listening",()=>{assert.deepEqual(FULL_SECTION_ORDER,["listening","reading","use-of-english","writing"]);const grade9=createFullSession(9,{},[],()=>.5,"2026-01-01T00:00:00.000Z");assert.equal(FULL_SECTION_ORDER[grade9.sectionIndex],"reading");assert.equal(grade9.listeningGroupId,undefined);assert.deepEqual(grade9.questionIds.listening,[]);assert.ok(resolveSessionQuestions(grade9).every(question=>question.section!=="listening"));for(const grade of[10,11]as const){const session=createFullSession(grade,{},[],()=>.5,"2026-01-01T00:00:00.000Z"),questions=resolveSessionQuestions(session);assert.equal(FULL_SECTION_ORDER[session.sectionIndex],"listening");assert.equal(session.listeningGroupId,"g"+grade+"-2022-listening");assert.equal(session.questionIds.listening.length,20);assert.ok(questions.some(question=>question.section==="listening"));assert.ok(questions.some(question=>question.section==="reading"));assert.ok(questions.some(question=>question.section==="use-of-english"))}});
test("senior Writing stays pending manual review material",()=>{for(const sets of[grade10WritingSets,grade11WritingSets]){assert.equal(sets.length,3);assert.ok(sets.every(set=>set.items[0].type==="writing"&&set.items[0].needsReview&&!set.items[0].acceptedAnswers.length))}});
test("senior adaptive bank reuses existing selection shape",()=>{for(const grade of[10,11]as const){const bank=adaptiveBankForSeniorGrade(grade);assert.ok(bank.length);assert.ok(bank.every(q=>q.grade===grade))}});

test("senior Listening sources use only official 2022 file playback",()=>{for(const path of["public/audio/grade-10/2022/listening.mp3","public/audio/grade-11/2022/listening.mp3"]){assert.ok(existsSync(path));assert.ok(statSync(path).size>1_000_000);assert.equal(readFileSync(path).subarray(0,3).toString("latin1"),"ID3")}for(const path of["source_materials/grade-10/2022/tasks_52_1668763415.pdf","source_materials/grade-10/2022/script_52_1668763452.pdf","source_materials/grade-10/2022/ans_52_1668763434.pdf","source_materials/grade-11/2022/tasks_52_1668763471.pdf","source_materials/grade-11/2022/script_52_1668763504.pdf","source_materials/grade-11/2022/ans_52_1668763482.pdf"]){assert.ok(existsSync(path));assert.ok(statSync(path).size>100_000)}assert.equal(grade10Listening2022.audioMode,"file");assert.equal(grade10Listening2022.audioSrc,"/audio/grade-10/2022/listening.mp3");assert.equal(grade10Listening2022.items.length,20);assert.deepEqual(grade10Listening2022.items.map(q=>q.acceptedAnswers[0]),["f","ns","t","t","f","t","ns","t","f","ns","c","b","c","a","c","f","a","c","d","e"]);assert.equal(grade11Listening2022.audioMode,"file");assert.equal(grade11Listening2022.audioSrc,"/audio/grade-11/2022/listening.mp3");assert.equal(grade11Listening2022.items.length,20);assert.deepEqual(grade11Listening2022.items.map(q=>q.acceptedAnswers[0]),["c","b","c","a","c","f","a","c","d","e","f","f","f","t","f","f","t","t","f","f"]);assert.equal(grade10Official2024.listening.items.length,0);assert.equal(grade11Registry[2024].listening.audioMode,"speech");assert.equal(grade11Registry[2024].listening.audioSrc,undefined);assert.match(grade11Registry[2024].listening.script||"",/eclipse/i)});

test("SAFE requires an allowlisted real MP3 and speech synthesis alone is never SAFE",()=>{assert.equal(validatedListeningGroupsForGrade(9).length,0);for(const grade of[10,11]as const){const groups=validatedListeningGroupsForGrade(grade);assert.equal(groups.length,1);assert.equal(isStrictlySafeListeningGroup(groups[0]),true);assert.equal(groups[0].grade,grade);assert.equal(groups[0].audioMode,"file");assert.match(groups[0].audioSrc,new RegExp("/audio/grade-"+grade+"/2022/listening\\.mp3"))}const speechOnly=listeningGroupsFromSets([grade11Registry[2024].listening],11)[0];assert.ok(speechOnly);assert.equal(speechOnly.audioMode,"speech");assert.equal(speechOnly.audioSrc,undefined);assert.equal(isStrictlySafeListeningGroup(speechOnly),false);const unverifiedFile={...speechOnly,audioMode:"file"as const,audioSrc:"/audio/missing.mp3",validation:{status:"safe",playback:"source-mp3",audioSource:"source_materials/missing.mp3",audioSha256:"0".repeat(64)}};assert.equal(existsSync("public/audio/missing.mp3"),false);assert.equal(isStrictlySafeListeningGroup(unverifiedFile),false)});

test("unsafe Listening assets are explicitly disabled and cannot enter the safe selector",()=>{assert.equal(disabledListeningGroups.length,7);assert.ok(disabledListeningGroups.some(group=>group.grade===9&&group.year===2024&&group.reason==="audio-transcript-mismatch"));assert.ok(disabledListeningGroups.some(group=>group.grade===10&&group.year===2024&&group.reason==="audio-transcript-mismatch"));assert.ok(disabledListeningGroups.some(group=>group.grade===11&&group.year===2023&&group.reason==="missing-key"));assert.ok(disabledListeningGroups.some(group=>group.grade===11&&group.year===2024&&group.reason==="missing-audio"&&group.audioSource===null));assert.ok(!disabledListeningGroups.some(group=>group.grade===10&&group.year===2022));assert.ok(!disabledListeningGroups.some(group=>group.grade===11&&group.year===2022));const safeAudioSources=[9,10,11].flatMap(grade=>validatedListeningGroupsForGrade(grade)).map(group=>group.validation.audioSource).filter(Boolean);assert.deepEqual(safeAudioSources,["https://reg.storage.yandexcloud.net/public/olymp_tasks/audio_52_1755785414.7z#10","https://reg.storage.yandexcloud.net/public/olymp_tasks/audio_52_1755785414.7z#11"])});

test("Grade 10 Listening uses the validated 2022 source instead of falling back to Grade 9",()=>{const source=readFileSync("data/questions/grade-10-11/index.ts","utf8"),groups=validatedListeningGroupsForGrade(10),selected=createStandaloneListeningSession("student",10,groups);assert.doesNotMatch(source,/grade9Official2024|adapt10/);assert.equal(grade10Official2024.listening.items.length,0);assert.equal(groups.length,1);assert.ok(selected);assert.equal(selected.group.id,"g10-2022-listening");assert.equal(selected.group.grade,10);assert.equal(selected.group.audioSrc,"/audio/grade-10/2022/listening.mp3");assert.ok(!selected.group.audioSrc?.includes("/grade-9/"));assert.equal(fullBankForGrade(10).listeningGroups.length,1);assert.equal(fullBankForGrade(10).listeningGroups[0].id,"g10-2022-listening")});


test("standalone Listening gates unavailable grades while validated senior groups can start",()=>{const standalone=readFileSync("components/training/GradeOfficialSection.tsx","utf8"),full=readFileSync("components/training/FullOlympiadTraining.tsx","utf8");assert.doesNotMatch(standalone,/audio\/grade-9/);assert.doesNotMatch(full,/audio\/grade-9/);assert.equal(createStandaloneListeningSession("student",9,validatedListeningGroupsForGrade(9)),null);assert.equal(FULL_SECTION_ORDER[createFullSession(9,{},[],()=>.5,"2026-01-01T00:00:00.000Z").sectionIndex],"reading");for(const grade of[10,11]as const){const attempt=createStandaloneListeningSession("student",grade,validatedListeningGroupsForGrade(grade));assert.ok(attempt);assert.equal(attempt.group.id,"g"+grade+"-2022-listening");assert.equal(FULL_SECTION_ORDER[createFullSession(grade,{},[],()=>.5,"2026-01-01T00:00:00.000Z").sectionIndex],"listening")}});
test("Standalone and Full Olympiad share the safe Listening registry",()=>{const standalone=readFileSync("components/training/GradeOfficialSection.tsx","utf8"),full=readFileSync("lib/full-olympiad.ts","utf8");assert.match(standalone,/validatedListeningGroupsForGrade\(grade\)/);assert.match(full,/validatedListeningGroupsForGrade\(grade\)/);for(const grade of[9,10,11])assert.deepEqual(fullBankForGrade(grade).listeningGroups,validatedListeningGroupsForGrade(grade))});
test("senior original banks provide ten complete Reading passages and seventy UOE questions",()=>{for(const grade of[10,11]as const){const reading=seniorOriginalReading(grade),uoe=seniorOriginalUseOfEnglish(grade);assert.equal(new Set(reading.map(q=>q.groupId)).size,10);assert.equal(reading.length,50);assert.equal(uoe.length,70);assert.equal(new Set([...reading,...uoe].map(q=>q.id)).size,120);assert.ok([...reading,...uoe].every(q=>q.source==="original-olympic-english-lab"&&q.acceptedAnswers.length===1))}});
test("Grade 10 Reading and UOE no longer contain the Grade 9 adapted fallback",()=>{assert.equal(grade10Official2024.reading.items.length,0);assert.equal(grade10Official2024["use-of-english"].items.length,0);for(const section of["reading","use-of-english"]as const){const bank=objectiveBankForSeniorGrade(10).filter(question=>question.section===section);assert.ok(bank.length>=50);assert.ok(bank.every(question=>question.grade===10&&!question.id.startsWith("g9-")&&!question.groupId?.startsWith("g9-")))}});
test("new senior answers and ids are structurally valid",()=>{for(const grade of[10,11]as const){const questions=[...seniorOriginalReading(grade),...seniorOriginalUseOfEnglish(grade)],ids=questions.map(question=>question.id);assert.equal(new Set(ids).size,ids.length);for(const question of questions){assert.equal(question.acceptedAnswers.length,1);if(question.options.length)assert.ok(question.options.some(option=>option.id===question.acceptedAnswers[0]),question.id)}}});
test("three consecutive senior attempts rotate passages and UOE material",()=>{
 for(const grade of[10,11]as const)for(const section of["reading","use-of-english"]as const){
  const original=seniorOriginalSet(grade,section)as QuestionSet;
  const official=grade===10?grade10Official2024[section]:grade11Registry[2024][section];
  const bank=selectableQuestions([original,official as QuestionSet],section as Section);
  let history={},last:string[]=[];
  const attempts:ReturnType<typeof createStandaloneSession>[]=[];
  for(let index=0;index<3;index++){
   const attempt=createStandaloneSession(`student-${grade}`,grade,section,bank,history,last,()=>.5,`2026-01-0${index+1}T00:00:00.000Z`);
   attempts.push(attempt);
   history=completeStandaloneHistory(history,attempt.questions,Object.fromEntries(attempt.questions.map(question=>[question.id,question.acceptedAnswers[0]])));
   last=attempt.session.questionIds;
  }
  for(let index=1;index<attempts.length;index++)assert.equal(attempts[index-1].session.questionIds.filter(id=>attempts[index].session.questionIds.includes(id)).length,0);
  if(section==="reading")for(const attempt of attempts)for(const group of new Set(attempt.questions.map(question=>question.groupId)))assert.deepEqual(attempt.questions.filter(question=>question.groupId===group).map(question=>question.id),bank.filter(question=>question.groupId===group).map(question=>question.id));
 }
});
test("grades 9, 10 and 11 each have three additional original manual-review prompts",()=>{for(const grade of[9,10,11]as const){const sets=originalWritingSets(grade);assert.equal(sets.length,3);assert.ok(sets.every(set=>(set.items[0]as unknown as{source:string}).source==="original-olympic-english-lab"&&set.items[0].needsReview&&!set.items[0].acceptedAnswers.length))}});
test("senior training UI displays the actual grade and renders audio from the selected group",()=>{const official=readFileSync("components/training/OfficialSection.tsx","utf8"),full=readFileSync("components/training/FullOlympiadTraining.tsx","utf8");assert.doesNotMatch(official,/grade===9\?"9 класс":"7–8 классы"/);assert.match(official,/set\.items\[0\]\?\.grade/);assert.match(full,/listeningGroup\.audioSrc/);assert.match(official,/\[A-F\]/);assert.match(full,/\[A-F\]/);assert.doesNotMatch(full,/grade===10\?"\/audio\/grade-10\/2024\/listening\.mp3"/)});
