import test from"node:test";import assert from"node:assert/strict";
import{grade9OriginalQuestionBank}from"../data/questions/grade-9/original/index.ts";
import{grade9Listening2022,grade9Reading2022,grade9UseOfEnglish2022}from"../data/questions/grade-9/official/2022/index.ts";
import{grade9Listening2023,grade9Reading2023,grade9UseOfEnglish2023}from"../data/questions/grade-9/official/2023/index.ts";
import{grade9Listening2024,grade9Reading2024,grade9UseOfEnglish2024}from"../data/questions/grade-9/official/2024/index.ts";
import type{QuestionBankItem,QuestionSet,Section}from"../data/questions/types.ts";
import{completeStandaloneHistory,createStandaloneListeningSession,createStandaloneSession,isResumableStandaloneSession,listeningGroupsFromSets,resolveStandaloneListeningGroup,resolveStandaloneQuestions,selectableQuestions,type StandaloneHistory}from"../lib/standalone-training.ts";
const studentId="student-audit-9";
const original=(section:Section):QuestionSet=>({id:`original-${section}`,title:section,section,instruction:"",items:grade9OriginalQuestionBank.filter(q=>q.section===section)as unknown as QuestionBankItem[]});
const keyed=(sets:QuestionSet[])=>sets.filter(set=>set.items.every(item=>item.acceptedAnswers.length&&!item.needsReview));
const banks={"use-of-english":selectableQuestions([original("use-of-english"),...keyed([grade9UseOfEnglish2022,grade9UseOfEnglish2023,grade9UseOfEnglish2024])],"use-of-english"),reading:selectableQuestions([original("reading"),...keyed([grade9Reading2022,grade9Reading2023,grade9Reading2024])],"reading"),listening:selectableQuestions(keyed([grade9Listening2022,grade9Listening2023,grade9Listening2024]),"listening")};
function audit(section:keyof typeof banks){const first=createStandaloneSession(studentId,9,section,banks[section],{},[],()=>.5,"2026-01-01T10:00:00.000Z"),answers=Object.fromEntries(first.questions.map(q=>[q.id,q.acceptedAnswers[0]])),history=completeStandaloneHistory({},first.questions,answers),second=createStandaloneSession(studentId,9,section,banks[section],history,first.session.questionIds,()=>.5,"2026-01-01T11:00:00.000Z");return{first,second}}
test("same student gets a new standalone attempt id and new Use of English ids",()=>{const{first,second}=audit("use-of-english");assert.equal(first.session.studentId,second.session.studentId);assert.notEqual(first.session.id,second.session.id);assert.notDeepEqual(first.session.questionIds,second.session.questionIds);assert.equal(first.session.questionIds.filter(id=>second.session.questionIds.includes(id)).length,0)});
test("Reading rotates complete passage groups",()=>{const{first,second}=audit("reading");assert.notDeepEqual(first.session.questionIds,second.session.questionIds);for(const attempt of[first,second])for(const group of new Set(attempt.questions.map(q=>q.groupId||q.id)))assert.deepEqual(attempt.questions.filter(q=>(q.groupId||q.id)===group).map(q=>q.id),banks.reading.filter(q=>(q.groupId||q.id)===group).map(q=>q.id))});
test("Listening runtime creates only an atomic validated Grade 9 group",()=>{const groups=listeningGroupsFromSets(keyed([grade9Listening2022,grade9Listening2023,grade9Listening2024]),9);assert.deepEqual(groups.map(group=>group.id),["g9-2024-listening"]);const first=createStandaloneListeningSession(studentId,9,groups,{},undefined,()=>.5,"2026-01-01T10:00:00.000Z");assert.ok(first);const second=createStandaloneListeningSession(studentId,9,groups,{},first.group.id,()=>.5,"2026-01-01T11:00:00.000Z");assert.ok(second);assert.notEqual(first.session.id,second.session.id);assert.deepEqual(first.session.questionIds,first.group.questions.map(q=>q.id));assert.equal(first.group.audioMode,"speech");assert.match(first.group.script||"",/solar eclipse/i);assert.equal(resolveStandaloneListeningGroup(first.session,groups)?.id,first.group.id);assert.deepEqual(resolveStandaloneListeningGroup(JSON.parse(JSON.stringify(first.session)),groups)?.questions.map(q=>q.id),first.session.questionIds)});
test("Listening resolver rejects audio group A with question ids from group B",()=>{const groups=listeningGroupsFromSets([grade9Listening2024],9),session=createStandaloneListeningSession(studentId,9,groups);assert.ok(session);assert.equal(resolveStandaloneListeningGroup({...session.session,questionIds:["foreign-question"]},groups),null)});
test("refresh restores standalone attempt B without selecting again",()=>{const{second}=audit("use-of-english"),stored=JSON.parse(JSON.stringify(second.session));assert.equal(stored.id,second.session.id);assert.deepEqual(resolveStandaloneQuestions(stored,banks["use-of-english"]).map(q=>q.id),second.session.questionIds)});
test("only an active matching standalone attempt can be restored",()=>{const{second}=audit("use-of-english");assert.equal(isResumableStandaloneSession(second.session,9,"use-of-english"),true);assert.equal(isResumableStandaloneSession({...second.session,status:"completed"},9,"use-of-english"),false);assert.equal(isResumableStandaloneSession(second.session,10,"use-of-english"),false)});
test("unseen then incorrect then remaining priority is enforced",()=>{const bank=banks["use-of-english"].slice(0,3),history:StandaloneHistory={[bank[0].id]:{seen:1,incorrect:0},[bank[1].id]:{seen:1,incorrect:1}};const selected=createStandaloneSession(studentId,9,"use-of-english",bank,history,[],()=>.5).questions;assert.equal(selected[0].id,bank[2].id);assert.equal(selected[1].id,bank[1].id)});
