import test from"node:test";import assert from"node:assert/strict";
import{readFileSync}from"node:fs";
import{displayCorrectAnswer,displayTeacherAnswer,findTeacherQuestion}from"../lib/teacher-attempt-questions.ts";
test("Grade 9 original question id resolves to full question text",()=>{const question=findTeacherQuestion("g9-lc-05");assert.ok(question);assert.ok(question.text.length>10)});
test("Grade 9 original multiple-choice key resolves to option text",()=>{const question=findTeacherQuestion("g9-lc-05")!;assert.notEqual(displayTeacherAnswer(question,"b"),"b");assert.ok(displayCorrectAnswer(question))});
test("Official 2024 question ids resolve with question and correct answer",()=>{const question=findTeacherQuestion("g9-2024-listening-14");assert.ok(question);assert.match(question.text,/According to the speaker/);assert.equal(displayTeacherAnswer(question,"a"),"spiritual experience");assert.equal(displayCorrectAnswer(question),"spiritual experience")});
test("Official 2024 gap-fill exposes the accepted answer",()=>{const question=findTeacherQuestion("g9-2024-use-of-english-01");assert.ok(question);assert.equal(displayTeacherAnswer(question,"outcomes"),"outcomes");assert.equal(displayCorrectAnswer(question),"outcomes")});
test("unknown question id keeps raw-answer fallback",()=>{assert.equal(findTeacherQuestion("missing-id"),undefined);assert.equal(displayTeacherAnswer(undefined,"b"),"b");assert.equal(displayCorrectAnswer(undefined),null)});
test("teacher attempt UI filters only incorrect objective answers",()=>{const source=readFileSync("components/teacher/TeacherViews.tsx","utf8");assert.match(source,/filter==="errors"\?objectiveAnswers\.filter\(answer=>answer\.is_correct===false\)/);assert.match(source,/>Только ошибки</)});

test("current 2025 official questions resolve in teacher results",()=>{const g78=findTeacherQuestion("vsosh-7-8-2025-listening-8"),g9=findTeacherQuestion("g9-2025-listening-15"),g11=findTeacherQuestion("g11-2025-listening-01");assert.ok(g78);assert.ok(g9);assert.ok(g11);assert.match(displayTeacherAnswer(g9,"a"),/worked in a shop/i);assert.match(displayCorrectAnswer(g11)||"",/worked in a shop/i)});
test("teacher Writing review selects only the writing answer from a full Olympiad attempt",()=>{const source=readFileSync("components/teacher/TeacherViews.tsx","utf8");assert.ok(source.includes('.eq("attempt_id",attemptId).eq("section","writing").single()'));assert.match(source,/fullOlympiad/)});

test("teacher can review Writing inline from the same full Olympiad attempt",()=>{const source=readFileSync("components/teacher/TeacherViews.tsx","utf8");assert.match(source,/id="writing-review"/);assert.match(source,/Проверить Writing/);assert.match(source,/review_writing_attempt/);assert.match(source,/WritingAnswerText/);assert.match(source,/data\.answers\.find\(answer=>answer\.section==="writing"\)/)});
