import type {QuestionBankItem,QuestionSet,Section} from "../data/questions/types.ts";
import type {AdaptiveQuestion} from "../data/questions/grade-7-8/original/types.ts";
import {originalQuestionBank} from "../data/questions/grade-7-8/original/index.ts";
import {grade782022Sets} from "../data/questions/grade-7-8/2022/index.ts";
import {grade9OriginalQuestionBank} from "../data/questions/grade-9/original/index.ts";
import {grade9Official2024} from "../data/questions/grade-9/official/2024/index.ts";
import {grade9Writing2022} from "../data/questions/grade-9/official/2022/index.ts";
import {grade9Writing2023} from "../data/questions/grade-9/official/2023/index.ts";
import {grade10WritingSets,grade11WritingSets,objectiveBankForSeniorGrade} from "../data/questions/grade-10-11/index.ts";
import {originalWritingSets} from "../data/questions/writing-original.ts";
import {listeningGroupsFromSets,seededRandom,selectListeningGroup,type ListeningGroup} from "./standalone-training.ts";
import {validatedListeningGroupsForGrade} from "./listening-registry.ts";

export const FULL_SECTION_ORDER=["listening","reading","use-of-english","writing"] as const;
export type FullSection=typeof FULL_SECTION_ORDER[number];
export type FullQuestion=QuestionBankItem&{options:string[]};
export type FullHistory=Record<string,{seen:number;incorrect:number}>;
export type FullSession={version:1;id:string;grade:number;startedAt:string;sectionIndex:number;questionIds:Record<Exclude<FullSection,"writing">,string[]>;listeningGroupId?:string;writingTaskId?:string;answers:Record<string,string>;writingText:string;completedAt?:string;writingStatus?:"pending"|"reviewed"|"local";writingReview?:{score:number;maxScore:number;comment?:string|null}};
export const FULL_ACTIVE_KEY="olympic-full-olympiad-active-v1";
export const FULL_HISTORY_KEY="olympic-full-olympiad-history-v1";
export const FULL_LAST_IDS_KEY="olympic-full-olympiad-last-ids-v1";

const normalizeAdaptive=(q:AdaptiveQuestion,grade:number):FullQuestion=>({
  ...q,grade:grade===9?9:"7-8",year:(q.year||2024) as 2022|2023|2024,stage:"municipal",source:q.source as QuestionBankItem["source"],sourceLabel:"OLYMPIC ENGLISH LAB",platformLabel:"Взлёт",options:q.options.map(o=>`${o.id.toUpperCase()} ${o.label}`),needsReview:!!q.needsReview,
} as FullQuestion);
const keyed=(items:readonly QuestionBankItem[])=>items.filter(q=>!q.needsReview&&q.acceptedAnswers.length);

export function fullBankForGrade(grade:number){
  const objective:FullQuestion[]=grade===10||grade===11
    ? objectiveBankForSeniorGrade(grade).map(q=>({...q,groupId:q.section==="listening"&&!q.groupId?`g${grade}-2024-listening-audio`:q.groupId}) as FullQuestion)
    : grade===9
    ? [...grade9OriginalQuestionBank.map(q=>normalizeAdaptive(q,9)),...FULL_SECTION_ORDER.slice(0,3).flatMap(section=>keyed(grade9Official2024[section].items).map(q=>({...q,groupId:section==="listening"&&!q.groupId?grade9Official2024.listening.id:q.groupId})))]
    : [...originalQuestionBank.map(q=>normalizeAdaptive(q,grade)),...FULL_SECTION_ORDER.slice(0,3).flatMap(section=>keyed(grade782022Sets[section].items).map(q=>({...q,groupId:section==="listening"&&!q.groupId?grade782022Sets.listening.id:q.groupId})))];
  const writingSets=grade===10?[...grade10WritingSets,...originalWritingSets(10)]:grade===11?[...grade11WritingSets,...originalWritingSets(11)]:grade===9?[grade9Writing2022,grade9Writing2023,grade9Official2024.writing,...originalWritingSets(9)]:[grade782022Sets.writing];
  const writings=writingSets.flatMap(set=>set.items) as FullQuestion[];
  const listeningGroups=grade>=9?validatedListeningGroupsForGrade(grade):listeningGroupsFromSets([grade782022Sets.listening],grade);
  return{objective:objective.filter(question=>question.section!=="listening"),listeningGroups,writing:writings[0],writings};
}

type Unit={id:string;items:FullQuestion[];priority:number;tie:number};
export function selectFullQuestions(bank:FullQuestion[],section:Exclude<FullSection,"writing">,history:FullHistory={},lastIds:string[]=[],target=10,random=Math.random){
  const candidates=bank.filter(q=>q.section===section&&!q.needsReview&&q.acceptedAnswers.length);
  const groups=new Map<string,FullQuestion[]>();
  candidates.forEach(q=>{const id=q.groupId||q.id;groups.set(id,[...(groups.get(id)||[]),q])});
  const last=new Set(lastIds),units:Unit[]=[...groups].map(([id,items])=>{const records=items.map(q=>history[q.id]);const unseen=records.some(record=>!record);const wrong=records.some(record=>record?.incorrect>0);const exactRepeat=items.every(q=>last.has(q.id));return{id,items,priority:(unseen?0:wrong?1:2)+(exactRepeat?3:0),tie:random()}}).sort((a,b)=>a.priority-b.priority||a.tie-b.tie);
  const selected:FullQuestion[]=[];for(const unit of units){selected.push(...unit.items);if(selected.length>=target)break}return selected;
}

const firstFullSectionIndex=(ids:FullSession["questionIds"])=>ids.listening.length?0:1;
export function nextFullSectionIndex(session:FullSession,from=session.sectionIndex){for(let index=from+1;index<FULL_SECTION_ORDER.length;index++){const section=FULL_SECTION_ORDER[index];if(section==="writing")return index;if((session.questionIds[section]||[]).length)return index}return from}

export function createFullSession(grade:number,history:FullHistory={},lastIds:string[]=[],random?:()=>number,now=new Date().toISOString()):FullSession{
  const id=globalThis.crypto?.randomUUID?.()||`full-${Date.now()}`,rng=random||seededRandom(id),{objective,listeningGroups,writings}=fullBankForGrade(grade),ids:FullSession["questionIds"]={listening:[],reading:[],"use-of-english":[]},lastListeningGroupId=lastIds.find(value=>listeningGroups.some(group=>group.id===value)),listeningGroup=selectListeningGroup(listeningGroups,history,lastListeningGroupId,rng);
  if(listeningGroup)ids.listening=listeningGroup.questions.map(question=>question.id);
  for(const section of ["reading","use-of-english"] as const)ids[section]=selectFullQuestions(objective,section,history,lastIds,10,rng).map(q=>q.id);
  const last=new Set(lastIds),writing=[...writings].sort((a,b)=>{const ar=history[a.id],br=history[b.id],ap=(!ar?0:ar.incorrect?1:2)+(last.has(a.id)?3:0),bp=(!br?0:br.incorrect?1:2)+(last.has(b.id)?3:0);return ap-bp||rng()-.5})[0];
  return{version:1,id,grade,startedAt:now,sectionIndex:firstFullSectionIndex(ids),questionIds:ids,...(listeningGroup?{listeningGroupId:listeningGroup.id}:{}),writingTaskId:writing?.id,answers:{},writingText:""};
}

export function resolveSessionWriting(session:FullSession){const bank=fullBankForGrade(session.grade);return bank.writings.find(task=>task.id===session.writingTaskId)||bank.writing}

export function updateFullHistory(history:FullHistory,questions:FullQuestion[],answers:Record<string,string>,isCorrect:(q:FullQuestion,a:string)=>boolean){const next={...history};for(const q of questions){const old=next[q.id]||{seen:0,incorrect:0},correct=isCorrect(q,answers[q.id]||"");next[q.id]={seen:old.seen+1,incorrect:old.incorrect+(correct?0:1)}}return next}
export function scoreFullObjectiveSections(questions:FullQuestion[],answers:Record<string,string>,isCorrect:(q:FullQuestion,a:string)=>boolean){const sections=FULL_SECTION_ORDER.slice(0,3)as Exclude<FullSection,"writing">[],rows=sections.map(section=>{const qs=questions.filter(q=>q.section===section),correct=qs.filter(q=>isCorrect(q,answers[q.id]||"")).length;return{section,correct,total:qs.length}}).filter(row=>row.total>0),correct=rows.reduce((n,row)=>n+row.correct,0),total=rows.reduce((n,row)=>n+row.total,0),percentage=total?Math.round(correct/total*100):0;return{rows,correct,total,percentage}}
export type FullReviewSection=Exclude<FullSection,"writing">;
export type FullReviewMode="mistakes"|"all";
export type FullReviewItem={id:string;section:FullReviewSection;number:number;text:string;userAnswer:string;correctAnswer:string;isCorrect:boolean;explanation:string;rule:string;evidence?:string};
const reviewSections=new Set<FullSection>(["listening","reading","use-of-english"]);
const genericExplanationPatterns=["ответ подтверждён официальным ключом","официальный ключ","official key","source-verified","keyed"];
const reviewStopWords=new Set(["the","and","for","that","this","with","from","which","what","when","where","why","how","are","was","were","will","would","could","should","have","has","had","into","about","your","you","his","her","its","their","they","them","who","whose","than","then","choose","complete","question","gap","which","person","paragraph","relates","read","text"]);
function reviewOptionKey(option:string){return option.match(/^[A-F](?=\s|$)/i)?.[0].toLowerCase()||option.trim().toLowerCase()}
function reviewAnswerLabel(question:FullQuestion,value:string|undefined){if(!value?.trim())return"—";const normalized=value.trim().toLowerCase(),option=question.options.find(item=>reviewOptionKey(item)===normalized||item.trim().toLowerCase()===normalized);if(option)return option;if(["t","f","ns"].includes(normalized))return normalized.toUpperCase();return value.trim()}
function meaningfulExplanation(question:FullQuestion){const text=(question.feedback||question.explanation||"").trim();if(!text)return"";const normalized=text.toLowerCase();return genericExplanationPatterns.some(pattern=>normalized.includes(pattern))?"":text}
function reviewSentences(source:string){return source.replace(/\s+/g," ").split(/(?<=[.!?])\s+|\n+/).map(sentence=>sentence.trim()).filter(Boolean)}
function reviewKeywords(text:string){return Array.from(new Set(text.toLowerCase().replace(/[^a-zа-яё0-9\s-]/gi," ").split(/\s+/).map(word=>word.trim()).filter(word=>word.length>3&&!reviewStopWords.has(word))))}
function clippedEvidence(sentence:string){return sentence.length>230?sentence.slice(0,227).trim()+"...":sentence}
function findEvidence(source:string|undefined,question:FullQuestion,correctAnswer:string){if(!source)return undefined;const normalizedCorrect=correctAnswer.toLowerCase();if(["t","f","ns"].includes(normalizedCorrect))return undefined;const keys=reviewKeywords(`${question.text} ${correctAnswer}`),sentences=reviewSentences(source);let best="",score=0;for(const sentence of sentences){const lower=sentence.toLowerCase(),current=keys.reduce((count,key)=>count+(lower.includes(key)?1:0),0)+(normalizedCorrect.length>3&&lower.includes(normalizedCorrect)?2:0);if(current>score){score=current;best=sentence}}return score>=2?clippedEvidence(best):undefined}
function wordFormationRule(question:FullQuestion,correctAnswer:string){const base=question.text.match(/\(([A-Z][A-Z-]+)\)/)?.[1],answer=correctAnswer.toLowerCase(),prefix=answer.match(/^(in|im|il|ir|un|dis|non)/)?.[1],suffix=answer.match(/(tion|sion|ment|ness|ity|ence|ance|ency|ant|ent|able|ible|ive|al|ful|less|ly|ing|ed|er|or|ous)$/)?.[1],part=suffix==="ly"?"наречие":suffix&&["tion","sion","ment","ness","ity","ence","ance","ency","er","or"].includes(suffix)?"существительное":suffix&&["able","ible","ive","al","ful","less","ous","ant","ent"].includes(suffix)?"прилагательное":"нужная часть речи";return `${base?`${base} -> ${correctAnswer}. `:""}В пропуске нужна форма слова, которая грамматически подходит к контексту: ${part}.${prefix?` Используется префикс ${prefix}-.`:""}${suffix?` Используется суффикс -${suffix}.`:""}`}
function ruleFor(question:FullQuestion,correctAnswer:string){if(question.rule?.trim())return question.rule.trim();const subskill=question.subskill.toLowerCase(),text=question.text.toLowerCase(),correct=correctAnswer.toLowerCase();if(question.section==="listening"){if(["t","f","ns"].includes(correct))return correct==="t"?"True: информация прямо подтверждается в аудио.":correct==="f"?"False: в аудио сказано противоположное утверждению.":"Not Stated: в аудио нет достаточной информации, чтобы подтвердить или опровергнуть утверждение.";return"Слушайте ключевые слова вопроса и их перефразирование: правильный вариант обычно подтверждается не теми же словами, а тем же смыслом."}if(question.section==="reading"){if(subskill.includes("reference")||text.includes("latter")||text.includes("former"))return'Для reference words найдите два ближайших возможных referent. "The latter" означает второй из двух названных предметов или идей.';if(subskill.includes("detail")||subskill.includes("scanning"))return"Найдите конкретную деталь в тексте и проверьте, что выбранный вариант не добавляет лишней информации.";if(subskill.includes("inference"))return"Inference строится на том, что следует из текста, но не противоречит ни одной детали.";if(subskill.includes("vocabulary"))return"Значение слова нужно выбирать по контексту предложения, а не по первому знакомому переводу.";return"Проверьте, где в тексте та же мысль выражена другими словами: ошибка часто возникает из-за paraphrase."}if(question.section==="use-of-english"){if(subskill.includes("word formation")||/\([A-Z][A-Z-]+\)/.test(question.text))return wordFormationRule(question,correctAnswer);if(subskill.includes("reference")||text.includes("latter")||text.includes("former"))return'"The latter" = второй из двух уже названных предметов или идей; "the former" = первый.';if(subskill.includes("vocab")||subskill.includes("collocation"))return"Выбирайте слово или выражение по значению в контексте и устойчивому сочетанию, а не по похожести формы.";return"Проверьте грамматическую конструкцию вокруг пропуска: управление, время, форма слова и устойчивое выражение должны совпадать с контекстом."}return"Сравните свой ответ с ключом и найдите место в задании, которое подтверждает правильный вариант."}
function explanationFor(question:FullQuestion,userAnswer:string,correctAnswer:string,isCorrect:boolean,evidence?:string){if(isCorrect)return"Ответ совпадает с ключом.";const own=meaningfulExplanation(question);if(own)return own;const correct=correctAnswer.toLowerCase();if(question.section==="listening"&&["t","f","ns"].includes(correct))return correct==="t"?"Утверждение должно быть отмечено True, потому что информация подтверждается в записи.":correct==="f"?"Правильный ответ False: запись сообщает противоположное утверждению.":"Правильный ответ Not Stated: в записи нет такой информации, поэтому нельзя выбрать True или False.";if(question.section==="listening")return evidence?"Правильный вариант подтверждается фрагментом аудирования; выбранный ответ не совпадает с ключевой информацией.":`Правильный ответ: ${correctAnswer}. Переслушайте фрагмент и обратите внимание на ключевые слова вопроса и их перефразирование в аудио.`;if(question.section==="reading")return evidence?"Правильный ответ подтверждается текстом. Ошибка, скорее всего, связана с неверно понятой деталью, paraphrase или выбором информации, которой нет в тексте.":"Правильный ответ подтверждается текстом, но короткое evidence автоматически не найдено. Перечитайте фрагмент вокруг ключевых слов вопроса.";if(question.section==="use-of-english")return `В этом задании нужен ответ ${correctAnswer}. Ваш вариант ${userAnswer||"—"} не подходит к грамматике или значению контекста.`;return`Правильный ответ: ${correctAnswer}.`}
export function buildFullQuestionReviews(questions:FullQuestion[],answers:Record<string,string>,isCorrect:(q:FullQuestion,a:string)=>boolean,{listeningScript=""}:{listeningScript?:string}={}){const groupPassages=new Map<string,string>();questions.forEach(question=>{if(question.passage)groupPassages.set(question.groupId||question.id,question.passage)});const counters:Record<FullReviewSection,number>={listening:0,reading:0,"use-of-english":0};return questions.filter(question=>reviewSections.has(question.section)).map(question=>{const section=question.section as FullReviewSection;const answer=answers[question.id]||"",correctRaw=question.acceptedAnswers[0]||"",correctAnswer=reviewAnswerLabel(question,correctRaw),userAnswer=reviewAnswerLabel(question,answer),source=question.evidence||question.passage||groupPassages.get(question.groupId||question.id)||(section==="listening"?listeningScript:""),evidence=question.evidence||findEvidence(source,question,correctAnswer),ok=isCorrect(question,answer);counters[section]+=1;return{id:question.id,section,number:counters[section],text:question.text,userAnswer,correctAnswer,isCorrect:ok,explanation:explanationFor(question,userAnswer,correctAnswer,ok,evidence),rule:ruleFor(question,correctAnswer),evidence}})}
export function resolveFullListeningGroup(session:FullSession):ListeningGroup|null{if(!session.listeningGroupId)return null;const ids=session.questionIds.listening||[],group=fullBankForGrade(session.grade).listeningGroups.find(candidate=>candidate.id===session.listeningGroupId);return group&&ids.length===group.questions.length&&ids.every((id,index)=>id===group.questions[index].id)?group:null}
export function isResumableFullSession(session:FullSession|null|undefined,grade:number):session is FullSession{if(!session||session.grade!==grade||session.completedAt)return false;const hasListening=(session.questionIds.listening||[]).length>0;return hasListening||session.listeningGroupId?!!resolveFullListeningGroup(session):true}
export function resolveSessionQuestions(session:FullSession){const bank=fullBankForGrade(session.grade),map=new Map([...bank.objective,...bank.listeningGroups.flatMap(group=>group.questions)].map(q=>[q.id,q]));return FULL_SECTION_ORDER.slice(0,3).flatMap(section=>(session.questionIds[section as keyof FullSession["questionIds"]]||[]).map(id=>map.get(id)).filter(Boolean)) as FullQuestion[]}
export function isSupportedFullGrade(grade:number){return[7,8,9,10,11].includes(grade)}
export type {Section,QuestionSet};
