"use client";
import Link from"next/link";import{ArrowLeft,MessageCircleMore,Mic2,Sparkles}from"lucide-react";import{useEffect,useMemo,useRef,useState}from"react";import{AppHeader}from"@/components/Brand";import Sidebar from"@/components/Sidebar";import{useProfile}from"@/components/ProfileBadge";import{speakingSets}from"@/data/speaking/2022/sets";import type{SpeakingSet}from"@/data/speaking/2022/types";import{submitSpeakingRecording,type SpeakingSubmissionMarker}from"@/lib/supabase/speaking-sync";import{ActiveSpeakingTask,rankSpeakingTasks,recordSpeakingAttempt,SPEAKING_ACTIVE_KEY,SPEAKING_HISTORY_KEY,type SpeakingHistory}from"@/lib/speaking-selection";import{createClient}from"@/lib/supabase/client";import SpeakingSetCard from"./SpeakingSetCard";import PreparationTimer from"./PreparationTimer";import FactFile from"./FactFile";import RequiredAspects from"./RequiredAspects";import SpeakingRecorder,{type SpeakingRecording}from"./SpeakingRecorder";import SpeakingCriteria from"./SpeakingCriteria";import SpeakingResult from"./SpeakingResult";
type Stage="sets"|"preparation"|"monologue"|"result";const read=<T,>(key:string,fallback:T):T=>{try{return JSON.parse(localStorage.getItem(key)||"")as T}catch{return fallback}};
export default function SpeakingWorkspace(){const profile=useProfile(),grade=Number(profile.grade),attemptIdRef=useRef(""),[stage,setStage]=useState<Stage>("sets"),[set,setSet]=useState<SpeakingSet|null>(null),[notes,setNotes]=useState(""),[history,setHistory]=useState<SpeakingHistory>({}),[result,setResult]=useState<{recording:SpeakingRecording;submission:SpeakingSubmissionMarker}|null>(null);
 // Restore only a task started by this grade; recording blobs themselves intentionally remain in memory.
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{const local=read<SpeakingHistory>(SPEAKING_HISTORY_KEY,{}),active=read<ActiveSpeakingTask|null>(SPEAKING_ACTIVE_KEY,null),task=active?.grade===grade?speakingSets.find(item=>item.id===active.taskId&&item.gradeRange.includes(grade)):null;setHistory(local);if(task&&active){attemptIdRef.current=active.attemptId;setSet(task);setStage("preparation")}createClient().from("speaking_submissions").select("task_id,status,score,max_score").then(({data})=>{if(!data)return;setHistory(current=>{let next={...current};for(const row of data){if(!row.task_id)continue;const percentage=row.status==="reviewed"&&row.score!=null&&row.max_score?Math.round(Number(row.score)/Number(row.max_score)*100):null,old=next[row.task_id]||{attempts:0,bestPercentage:null};next={...next,[row.task_id]:{attempts:Math.max(1,old.attempts),bestPercentage:percentage==null?old.bestPercentage:Math.max(old.bestPercentage??0,percentage)}}}localStorage.setItem(SPEAKING_HISTORY_KEY,JSON.stringify(next));return next})})},[grade]);
 useEffect(()=>()=>{if(result?.recording.url)URL.revokeObjectURL(result.recording.url)},[result]);const lastTaskId=Object.keys(history).at(-1)||null,available=useMemo(()=>rankSpeakingTasks(speakingSets,grade,history,lastTaskId),[grade,history,lastTaskId]);
 const choose=(next:SpeakingSet)=>{const attemptId=crypto.randomUUID();attemptIdRef.current=attemptId;localStorage.setItem(SPEAKING_ACTIVE_KEY,JSON.stringify({grade,taskId:next.id,attemptId}));setSet(next);setStage("preparation");window.scrollTo({top:0,behavior:"smooth"})};
 const submit=async(recording:SpeakingRecording)=>{if(!set)return;const submission=await submitSpeakingRecording({attemptId:attemptIdRef.current||crypto.randomUUID(),blob:recording.blob,startedAt:recording.startedAt,durationSeconds:recording.duration,grade,task:set}),nextHistory=recordSpeakingAttempt(history,set.id);setHistory(nextHistory);localStorage.setItem(SPEAKING_HISTORY_KEY,JSON.stringify(nextHistory));localStorage.removeItem(SPEAKING_ACTIVE_KEY);setResult({recording,submission});setStage("result");window.scrollTo({top:0,behavior:"smooth"})};
 const reset=()=>{attemptIdRef.current="";localStorage.removeItem(SPEAKING_ACTIVE_KEY);setStage("sets");setSet(null);setNotes("");setResult(null)};
 if(stage==="result"&&set&&result)return <main className="portal training speaking-page"><AppHeader blue/><div className="speaking-result-shell"><SpeakingResult set={set} profile={profile} duration={result.recording.duration} audioUrl={result.recording.url} submission={result.submission} onAgain={reset}/><SpeakingCriteria criteria={set.criteria}/></div></main>;
 return <main className="portal training speaking-page"><AppHeader blue/><div className="speaking-layout"><Sidebar active="Speaking"/><section className="speaking-main"><nav className="speaking-breadcrumb"><Link href="/dashboard"><ArrowLeft/>Главная</Link><span>Speaking · {grade} класс</span></nav><header className="speaking-hero"><div className="hero-mic"><Mic2/><i/><i/></div><div><span>SPEAKING CHALLENGE</span><h1>Олимпиадная тренировка <em>устной речи</em></h1><p>Подготовься к выступлению, раскрой все пункты и запиши ответ.</p></div><aside><b>{profile.firstName} {profile.lastName}</b><small>{profile.grade} класс{profile.classLetter?`, ${profile.classLetter}`:""}</small></aside></header>{stage==="sets"&&<><div className="section-heading"><div><span>01 · ВЫБЕРИ ЗАДАНИЕ</span><h2>Speaking Challenges</h2></div><p>Сначала — новые задания, затем темы для дополнительной практики</p></div><div className="speaking-sets">{available.map(item=><SpeakingSetCard key={item.id} set={item} onStart={choose}/>)}</div><SpeakingCriteria criteria={speakingSets[0].criteria}/></>}{stage==="preparation"&&set?.factFile&&<><div className="stage-banner"><span>01</span><div><small>PREPARATION</small><h2>{set.title}</h2></div><PreparationTimer seconds={set.preparationTime} onDone={()=>setStage("monologue")}/></div><div className="preparation-grid"><FactFile sections={set.factFile}/><aside><RequiredAspects aspects={set.requiredAspects}/><label className="notes"><b>Мои заметки</b><small>Во время ответа пользоваться записями нельзя.</small><textarea value={notes} onChange={event=>setNotes(event.target.value)} placeholder="Короткие опорные слова и идеи…"/></label>{set.followUpQuestions&&<FollowUps questions={set.followUpQuestions}/>}</aside></div></>}{stage==="monologue"&&set&&<><div className="stage-banner monologue"><span>02</span><div><small>MONOLOGUE · 3–4 MINUTES</small><h2>{set.instructions}</h2></div></div><div className="monologue-grid"><section><RequiredAspects aspects={set.requiredAspects} compact/><SpeakingRecorder onSubmit={submit}/></section><aside><div className="notes-hidden"><Sparkles/><h3>Заметки скрыты</h3><p>Во время ответа пользоваться записями нельзя.</p></div><SpeakingCriteria criteria={set.criteria}/>{set.followUpQuestions?<FollowUps questions={set.followUpQuestions}/>:<div className="dialogue-later"><MessageCircleMore/><h3>Dialogue practice</h3><p>Следующий этап предполагает вопросы и взаимодействие с собеседником.</p></div>}</aside></div></>}</section></div></main>}
function FollowUps({questions}:{questions:string[]}){return <div className="dialogue-later"><MessageCircleMore/><h3>Follow-up questions</h3><ol>{questions.map(question=><li key={question}>{question}</li>)}</ol></div>}
